from selenium.webdriver.common.by import By


accounts_headers_cta = (By.XPATH, '//*[contains(@class, "addAccountCTA")]/button[contains(@class, "settingBtn")][index]')
accounts_head_col = (By.XPATH, '(//span[contains(@class, "ag-header-cell-text")])')
add_accounts_btn = (By.XPATH, '//*[contains(@class, "addAccountCTA")]/button[contains(text(), "Add New Account")]')
acc_basic_info_txt = (By.XPATH, '//h3[contains(text(), "Account Basic Information")]')
cancel_btn = (By.XPATH, '//button[contains(text(), "Cancel")]')
save_btn = (By.XPATH, '//button[contains(text(), "Save")]')
paste_image_loc = (By.XPATH, '//div[contains(@class, "paste-img")]')
acc_field_txtbox = (By.XPATH, '//input[@name="field_name"]')       #accountName
country_dd_loc = (By.XPATH, '//div[contains(@class, "countryFlagCode")]')
country_search_txtbox = (By.XPATH, '//input[contains(@placeholder, "Search Country")]')
start_month = (By.XPATH, '//select[@id= "startMonth"]')
start_month_list = (By.XPATH, '(//select[@id= "startMonth"]/option)')
rm_norms = (By.XPATH, '//select[@id="rmNormsRateTypeId"]')
rm_norms_options = (By.XPATH, '(//select[@id="rmNormsRateTypeId"]/option)')
tnc_loc = (By.XPATH, '//*[@id="terms"]')
# pan = panNo, start month is * startMonth, RM norms = rmNormsRateTypeId, customer code = customerCode,
# working days = noOfWorkingDays, t&c = terms, business nature = businessNatureIds, domain id = businessDomainIds,
# segment = segmentIds, paymnt = paymentMethodId, payment term = paymentTermId,

business_info_h3 = (By.XPATH, '//h3[contains(text(), "Business Information")]')
business_nature = (By.XPATH, '//*[contains(text(), "Select Business Nature")]')
business_nature_option = (By.XPATH, '(//*[contains(@name, "businessNatureIds")]//input/..)')
business_nature_option_txt = (By.XPATH, '(//*[contains(@name, "businessNatureIds")]//div)')
business_nature_selected = (By.XPATH, '(//*[text()= "Business Nature"]/parent::*//span[@class="selected-item"])')
business_domain = (By.XPATH, '//*[contains(text(), "Select Business Domain")]')
business_domain_option = (By.XPATH, '(//*[contains(@name, "businessDomainIds")]//input/..)')
business_domain_option_txt = (By.XPATH, '(//*[contains(@name, "businessDomainIds")]//div)')
business_domain_selected = (By.XPATH, '(//*[text()= "Business Domain"]/parent::*//span[@class="selected-item"])')
business_segment = (By.XPATH, '//*[contains(text(), "Select Business Segment")]')
business_segment_option = (By.XPATH, '(//*[contains(@name, "segmentIds")]//input/..)')
business_segment_option_txt = (By.XPATH, '(//*[contains(@name, "segmentIds")]//div)')
business_segment_selected = (By.XPATH, '(//*[text()= "Business Segment"]/parent::*//span[@class="selected-item"])')


payment_details_h3 = (By.XPATH, '//h3[contains(text(), "Payment Details")]')
payment_method = (By.XPATH, '//select[@id="paymentMethodId"]')
payment_method_options = (By.XPATH, '(//select[@id="paymentMethodId"]/option)')
payment_term = (By.XPATH, '//select[@id="paymentTermId"]')
payment_term_options = (By.XPATH, '(//select[@id="paymentTermId"]/option)')

Billing_Address1_h3 = (By.XPATH, '//h3[contains(text(), "Billing Address 1")]')
billing_country = (By.XPATH, '(//*[contains(@id, "billingCountry")])')
billing_country_options = (By.XPATH, '(//*[contains(@id, "billingCountry")]/option)')
billing_country_select = (By.XPATH, '//*[contains(@id, "billingCountry")]/option[contains(text(),"country_name")]')
billing_state = (By.XPATH, '(//*[contains(@id, "billingState")])')
billing_state_options = (By.XPATH, '(//*[contains(@id, "billingState")]/option)')
billing_state_select = (By.XPATH, '//*[contains(@id, "billingState")]/option[contains(text(),"state_name")]')
billing_city = (By.XPATH, '(//*[contains(@id, "billingCity0")])')
billing_city_options = (By.XPATH, '(//*[contains(@id, "billingCity0")]/option)')
billing_city_select = (By.XPATH, '//*[contains(@id, "billingCity0")]/option[contains(text(),"city_name")]')
billing_txt_box = (By.XPATH, '(//*[contains(@id, "billingTxtBox")])')

#  state //*[contains(@id, "billingState")], city = billingCity, address = billingAddress, postal = billingPostalCode
# gst = gstin


shipping_add_yes = (By.XPATH, '//*[contains(text(), "Shipping Address")]/following-sibling::div[contains(@class, "question")]//span[text()= "Yes"]')
primary_add_yes = (By.XPATH, '//*[contains(text(), "Primary Billing")]/following-sibling::div[contains(@class, "question")]//span[text()= "Yes"]')
add_new_billing_btn = (By.XPATH, '//*[contains(text(), " Add New Billing Address ")]')

accounts_table_row_loc_a = (By.XPATH, '(//div[@row-index="0"]//*[contains(@class, "ag-cell-value")]//a)')
accounts_table_row_loc = (By.XPATH, '(//div[@row-index="0"]//*[contains(@class, "ag-cell-value")]/span)')
accounts_name_row_loc = (By.XPATH, '//a[contains(text(), "name")]/../../..')
accounts_details_sidebar_rfq = (By.XPATH, '//*[@class="main-content"]//li[contains(text(), "RFQ")]')
accounts_details_rfq_cta = (By.XPATH, '//a[contains(text(), "RFQ")]')

accounts_norms = (By.XPATH, '//button[contains(text(), "Norms")]')
norms_type = (By.XPATH, '(//*[contains(@name, "normsType")])')
norms_type_options = (By.XPATH, '(//*[contains(@name, "normsType")]/option)')
fiscal_year = (By.XPATH, '(//*[contains(@name, "fiscalYear")])')
fiscal_year_options = (By.XPATH, '(//*[contains(@name, "fiscalYear")]/option)')
norms_filter = (By.XPATH, '(//*[contains(@name, "normsFilter")])')
norms_filter_options = (By.XPATH, '(//*[contains(@name, "normsFilter")]/option)')
effective_from = (By.XPATH, '(//*[contains(@for, "effectiveFrom")]/..//input)')
effective_till = (By.XPATH, '(//*[contains(@for, "effectiveTill")]/..//input)')
manuf_location = (By.XPATH, '(//*[contains(@name, "mfgLocation")])')
manuf_location_options = (By.XPATH, '(//*[contains(@name, "mfgLocation")]/option)')
acc_business_nature = (By.XPATH, '(//*[contains(@name, "accountBusinessNature")])')
acc_business_nature_options = (By.XPATH, '(//*[contains(@name, "accountBusinessNature")]/option)')
bop_norms_text = (By.XPATH, '//label[contains(text(), "BOP Norms Based on Account Nature")]')
currency_norms_text = (By.XPATH, '//label[contains(text(), "Currency Information")]')
mhr_norms_text = (By.XPATH, '//label[contains(text(), "MHR Norms Based on Account Nature")]')
process_norms_text = (By.XPATH, '//label[contains(text(), "Flat MHR Norms Based on Account Nature")]')
over_head_text = (By.XPATH, '//label[contains(text(), "Over Head Information")]')
raw_material_norms_text = (By.XPATH, '//label[contains(text(), "RM Norms Based on Account Nature")]')
rm_norms_table_header_loc = (By.XPATH, '(//div[@ref="eLabel"]/span[1])')
rm_norm_row_value_loc = (By.XPATH, '(//div[@role="gridcell"])')
h1_rate_loc = (By.XPATH, '(//div[@col-id="h1Rate"])[2]')
h1_rate_input_loc = (By.XPATH, '(//div[@col-id="h1Rate"])[2]//input')
h1_scrap_rate_loc = (By.XPATH, '(//div[@col-id="h1ScrapRate"])[2]')
h1_scrap_rate_input_loc = (By.XPATH, '(//div[@col-id="h1ScrapRate"])[2]//input')
other_norms_descriptions_col_loc = (By.XPATH, '//div[@role="gridcell" and position() mod 2 = 1]')
norms_flat_rate_loc = (By.XPATH, '(//div[@col-id = "flatRate"])[num]')
norms_percentage_rate_loc = (By.XPATH, '(//div[@col-id = "percentRate"])[num]')
norms_applicable_on_loc = (By.XPATH, '(//div[@col-id = "overHeadsapplicableOn"])[num]//div[@class="multiselect-dropdown"]')
norms_applicable_options_loc = (By.XPATH, '((//div[@class="dropdown-list"])[num]//input[@type="checkbox"])')

process_norms_table_headers = (By.XPATH, '(//div[contains(@class, "d-flex")])')
process_norms_table_details = (By.XPATH, '//table[contains(@class, "generic-table")]//tbody//span')
process_norms_table_process_uit = (By.XPATH, '//table[contains(@class, "generic-table")]//tbody//select')
process_norms_table_new_rate = (By.XPATH, '//table[contains(@class, "generic-table")]//tbody//input')
over_head_table_headers = (By.XPATH, '(//span[@ref="eText"])')
over_head_table_col1 = (By.XPATH, '(//div[@col-id="overHeadName"])')
over_head_table_col2 = (By.XPATH, '(//div[@col-id="oldRate"])')
over_head_table_col3 = (By.XPATH, '(//div[@col-id="flatRate"])')
over_head_table_col4 = (By.XPATH, '(//div[@col-id="percentRate"])')
over_head_table_col5 = (By.XPATH, '(//div[@col-id="overHeadsapplicableOn"])')
over_head_table_applicable_options = (By.XPATH, '(//ul[@class="item2"])[index]//li')
accounts_nav_name_loc = (By.XPATH, '//div[@class="rfqSection"]//td[contains(text(), "acc_name")]')

accnt_details_header_loc = (By.XPATH, '//*[contains(@class,"secTitle") and contains(text(),"Account Details")]')
account_details_cols_locs = (By.XPATH, '(//*[contains(@id,"rfqdet2")]//*[contains(@class,"customTable")]//th[contains(text(),"field")])')
accnt_details_values_locs = (By.XPATH, '//*[contains(@id,"rfqdet2")]//*[contains(@class,"customTable")]//th[contains(text(),"feild")]/following-sibling::td')

address_details_header_loc = (By.XPATH, '//*[contains(@class,"rfqSection")]//*[contains(text(),"Address Details")]')
primary_billing_address_loc = (By.XPATH, '//h4[contains(text(),"Primary Billing Address")]')
billing_address_txt_loc = (By.XPATH, '//h4[contains(text(),"Primary Billing Address")]/following-sibling::p')
primary_shipping_address_txt_loc = (By.XPATH, '//h4[contains(text(),"Primary Shipping Address")]/following-sibling::p')
raw_material_cols = (By.XPATH, '(//div[@role="gridcell" and position()])')

mhr_data_cols_loc = (By.XPATH, '//*[contains(@class,"field")]//input')
machine_name_selec_loc = (By.XPATH, '//*[contains(@class,"machineNameId ")]//select')
machine_name_options_loc = (By.XPATH, '(//*[contains(@class,"machineNameId ")]//select//option)')
mhr_info_process_selec_loc = (By.XPATH, '//*[contains(@class,"processId ")]//select')
mhr_info_options_loc = (By.XPATH, '(//*[contains(@class,"processId ")]//select//option)')
oum_info_col_loc = (By.XPATH, '//*[contains(@class,"uomId")]//select')
oum_info_options_loc = (By.XPATH, '(//*[contains(@class,"uomId ")]//select//option)')
machine_variable_header_loc = (By.XPATH, '//*[contains(text(),"Machine Variables ")]')
space_rental_cost_header_loc = (By. XPATH, '//*[contains(text(),"Space Rental Cost")]')
finance_cost_header_loc = (By.XPATH, '//*[contains(text(),"Finance Cost")]')
man_power_cost_header_loc = (By.XPATH, '//*[contains(text(),"Manpower Cost")]')
electricity_cost_header_loc = (By.XPATH, '//*[contains(text(),"Electricity Cost")]')
other_cost_header_loc = (By.XPATH, '//*[contains(text(),"Other Cost")]')

process_norms_table_data_loc = (By.XPATH, '(//*[contains(@class,"generic-table")]//tbody//tr)')
process_norms_table_new_rate_loc = (By.XPATH, '(//table[contains(@class, "generic-table")]//input[@type="number"])')
