from selenium.webdriver.common.by import By


add_contact_btn = (By.XPATH, '//button[contains(text(), "Add New Contacts")]')
contact_info_txt = (By.XPATH, '//h3[contains(text(), "Contact Information")]')
contact_acc_name = (By.XPATH, '//*[@for="accountName"]/..//input')
contact_acc_name_highlight = (By.XPATH, '//span[@class="highlight-text"]')
name_title = (By.XPATH, '//*[@name="title" ]')
contact_field_txtbox = (By.XPATH, '//*[@id="field_name"]')
mobile_field_txtbox = (By.XPATH, '//*[@name="mobileNumber"]')
# txtbox ids    firstName, lastName, email, mobileNumber, phoneNumber,

contact_logo = (By.XPATH, '//input[@id="logo"]')
accept_uploaded_image = (By.XPATH, '//button[contains(text(), "Accept")]')
uploaded_img = (By.XPATH, '//img[@alt="Uploaded image"]')
select_title = (By.XPATH, '//*[@id="title"]')
select_title_options = (By.XPATH, '(//select[@id= "title"]/option)')
select_department = (By.XPATH, '//*[@id="departmentId"]')
select_department_options = (By.XPATH, '(//select[@id= "departmentId"]/option)')
select_designation = (By.XPATH, '//*[@id="designationId"]')
select_designation_options = (By.XPATH, '(//select[@id= "designationId"]/option)')
select_report_to = (By.XPATH, '//*[@id="reportTo"]')
select_report_to_options = (By.XPATH, '(//select[@id= "reportTo"]/option)')
select_gender = (By.XPATH, '//*[@id="gender"]')
select_gender_options = (By.XPATH, '(//select[@id= "gender"]/option)')
select_date = (By.XPATH, '(//input[@placeholder="select Date"])')
select_marital_status = (By.XPATH, '//*[@id="maritalStatus"]')
select_marital_options = (By.XPATH, '(//select[@id= "maritalStatus"]/option)')
check_email_option = (By.XPATH, '//input[@id="emailOptIn"]')
send_greetings_yes = (By.XPATH, '//label[contains(text(), "Send Greetings")]/..//div[@class="yes text-center"]')
send_acknowledgement_yes = (By.XPATH, '//label[contains(text(), "Send Acknowledgement")]/..//div[@class="yes text-center"]')

official_address_txt = (By.XPATH, '//*[contains(text(), "Official Address")]')
residential_address_txt = (By.XPATH, '//h3[contains(text(), "Residential Address")]')

contact_billing_country = (By.XPATH, '(//*[contains(@id, "country")])')
contact_billing_country_options = (By.XPATH, '((//*[contains(@id, "country")])[index]/option)')
contact_billing_country_select = (By.XPATH, '(//*[contains(@id, "country")])[index]/option[contains(text(),"country_name")]')
contact_billing_state = (By.XPATH, '(//*[contains(@id, "state")])')
contact_billing_state_options = (By.XPATH, '((//*[contains(@id, "state")])[index]/option)')
contact_billing_state_select = (By.XPATH, '(//*[contains(@id, "state")])[index]/option[contains(text(),"state_name")]')
contact_billing_city = (By.XPATH, '(//*[contains(@id, "city")])')
contact_billing_city_options = (By.XPATH, '((//*[contains(@id, "city")])[index]/option)')
contact_billing_city_select = (By.XPATH, '(//*[contains(@id, "city")])[index]/option[contains(text(),"city_name")]')