from selenium.webdriver.common.by import By
from test_data.testdata import *

# General
SKIP_X_BTN_GENERIC = (By.XPATH, '//A[@data-step="skip"]')
MAIN_LOGO = (By.XPATH, '//A[@alt="promo logo"]')
MAIN_LOGO_TEMPLATE_PAGE = (By.XPATH, '//SPAN[@class="desktop-header__logo"]')
OK_BUTTON = (By.XPATH, '//SPAN[@class="md-accept"][text()="OK"]')

# Main Page
AGREE_COOKIES_BUTTON = (By.XPATH, "//*[text()='Agree & Continue']")
AGREE_COOKIES_NEXT = (By.XPATH, "//BUTTON[@class='got-it-btn']")
HOME_LOGIN_BUTTON = (By.XPATH, "//*[@data-qaid='header_login_button']")
LOGIN_MOBILE_BUTTON = (By.XPATH, "//A[@class='new-auth sidebar__link signin']")
SIGNUP_BUTTON = (By.XPATH, "//*[@class='signup signup--round']")
USER_EMAIL_TEXTBOX = (By.XPATH, "//INPUT[@id='sui-email']")
USER_PASSWORD_TEXTBOX = (By.XPATH, "//INPUT[@id='sui-password']")
LOGIN_BUTTON = (By.XPATH, "//*[@type='submit'][@value='Login']")
EMPTY_FIELD_ERROR = (By.XPATH, "//*[text()='Oops! This field can’t be empty']")
LOGIN_PASS_FIELD_ERROR = (By.XPATH, '//SPAN[@class="promo__input-message"]')
WRONG_CREDS_ERROR = (By.XPATH, "//*[text()='Darn! Your email or password is incorrect']")
LOGIN_FRAME = (By.XPATH, "//IFRAME[@data-qaid='auth_dialog_iframe']")
CLOSE_BUTTON = (By.XPATH, "//DIV[@class='close-btn']")
HELP_US_TEXT = (By.XPATH, "//H1[text()='Help us get to know you better']")
TRY_FREE = (By.CSS_SELECTOR, '[data-qaid=landing_try-for-free_button]')
GO_TO_PRICING = (By.CSS_SELECTOR, '[data-qaid=header_link_pricing]')

# Image Resizer
TOOLS_BTN = (By.XPATH, '//A[@data-qaid="header_make"][text()="Tools "]')
IMAGE_RESIZER_BTN = (By.XPATH, '//A[@data-qaid="header_submenu_image-resizer"]')
IR_UPLOAD_PATH = (By.XPATH, '//DIV[text()="Browse"]/input')
IR_IMAGE_UPLOADED_BOX = (By.XPATH, '//DIV[@class="cropper-wrap-box"]')
IR_WIDTH_TXT = (By.XPATH, '(//INPUT[@class="InputWithLabel-module--inputWithLabelInput--3Efov"])[1]')
IR_HEIGHT_TXT = (By.XPATH, '(//INPUT[@class="InputWithLabel-module--inputWithLabelInput--3Efov"])[2]')
IR_RATIO_CHECKBOX = (By.XPATH, '//DIV[@class="checkbox-module--checkbox--2NG3Z"]')
IR_DOWNLOAD_BUTTON = (By.XPATH, '(//BUTTON[text()="Download"])[1]')
PROMO_AD_POP_UP = (By.XPATH, '(//A[text()="Try for free"])[1]')
PROMO_IR_SIGN_UP_POPUP = (By.XPATH, '//*[text()="Sign up to download your content"]')
IR_SIGN_UP = (By.XPATH, '//A[text()="Sign up"]')
IR_LOGIN = (By.XPATH, '(//A[text()="Login"])[1]')
PROMO_AD_POP_UP_CLS = (By.XPATH, '(//img[@alt="Close"])[1]')
PROMO_IR_SIGN_UP_POPUP_CLS = (By.XPATH, '//DIV[@class="promo__icon Dark01-bg promo__icon--medium"]')
IR_SIDE_ICONS = (By.XPATH, '(//DIV[@class="ir-aside__icon"])')
IR_RATIO_BTN = (By.XPATH, '(//DIV[@class="index-module--selectImageWrapper--M14XA"])')
IR_RATIO_SELECT = (By.XPATH, '(//DIV[@data-social="Facebook"])')
IR_DOWNLOAD_SELECTED_BUTTON = (By.XPATH, '//BUTTON[text()="Download Selected Images"]')
IR_CONVERT_TO_VIDEO_BTN = (By.XPATH, '(//BUTTON[text()="Convert to video"])[1]')
IR_IMG_PRESENT = (By.XPATH,
                  '//DIV[@class="mainImage-module--mainImage--BlqSp mainImage-module--mainImageLoaded--OMJDb"]')
IR_REPLACE_IMAGE_BTN = (By.XPATH, '//button[normalize-space()="Replace Image"]')

# Login and Signup
LOGIN_BTN = (By.XPATH, '//*[@data-qaid="header_login_button"]')
SIGNUP_BTN = (By.XPATH, "//*[@data-qaid='header_signup_button']")  # don't change it until tags will be unify a/div
AUTH_FRAME = (By.XPATH, '//IFRAME[@data-qaid="auth_dialog_iframe"]')
CLOSE_AUTH_IFRAME = (By.XPATH, '//IFRAME[@data-qaid="auth_dialog_close_button"]')
FULL_NAME_INPUT = (By.XPATH, '//INPUT[@data-qaid="reg_input_name"]')
EMAIL_INPUT = (By.XPATH, '//INPUT[@data-qaid="reg_input_email"]')
PASS_INPUT = (By.XPATH, '//INPUT[@data-qaid="reg_input_password"]')
LOGIN_FRAME_BTN = (By.XPATH, '//INPUT[@data-qaid="login_submit_button"]')
SIGNUP_FRAME_BTN = (By.XPATH, '//INPUT[@data-qaid="reg_submit_button"][@class="submit"]')
USERNAME_MENU = (By.XPATH, '//*[@data-qaid="header_profile_menu"]')
WHAT_DO_YOU_DO_INDUSTRY = (By.XPATH, '//DIV[@class="business-type"]/div[1]/div[1]')
WHAT_DO_YOU_DO_SPECIALIZATION = (By.XPATH, '//DIV[@class="business-type"]/div[1]/div[1]')
FREE_PLAN_MODAL = (By.XPATH, '//SPAN[text()="Welcome to your Promo.com Free Plan!"]')
APPCUES_FRAME = (By.XPATH, '//IFRAME[@src="about:blank"][@role="dialog"]')
APPCUES_GET_STARTED = (By.XPATH, '//A[@class="appcues-button appcues-button-success"]')
APPCUES_CLOSE_FRAME = (By.XPATH, '/html/body/appcues/div/a')
POPUP_GENERIC = (By.XPATH, '//DIV[@class="generic-popup"]')
POPUP_CUSTOM_FONT_SEE = (By.XPATH, '//BUTTON[@class="see-plans"]')
NONE_APPLIES_BTN = (By.XPATH, '//DIV[@class="none"][text()="None of the above applies"]')
NEXT_BTN = (By.XPATH, '//DIV[@class="next"][text()="Next"]')
SKIP_OFFER_MODAL_BTN = (By.XPATH, '//A[@data-step="skip"]')
SKIP_OFFER_MODAL_FRAME = (By.XPATH, '//DIV[@class="appcues"]/appcues-container[1]/iframe[1]')
ONBOARDING_DONT_HAVE_WEBSITE = (By.XPATH, '//BUTTON[text()="I don’t have a website"]')
CLOSE_ONBOARDING_POPUP = (By.XPATH, '//DIV[@class="onboarding-popup__close-button"]')
CLOSE_ONBOARDING_POPUP_NEW = (By.XPATH, '//DIV[@class="onBoarding-header__close-button"]')
APPCUES_CLOSE_CLAIM_OFFER_POPUP = (By.XPATH, '//a[@aria-label="Close modal"]')
APPCUES_CLAIM_OFFER_IFRAME = (By.XPATH, '/html/body/div[17]/appcues-container/iframe')
START_CREATING_BTN = (By.XPATH, '//BUTTON[text()="Start Creating"]')

# New Authentication
MAIN_LOGO_NEW = (By.XPATH, '//A[@data-qaid="main_logo"]')
SIGNUP_EMAIL = (By.XPATH, '//INPUT[@data-qaid="signup_email"]')
SIGNUP_FULL_NAME = (By.XPATH, '//INPUT[@data-qaid="signup_full_name"]')
SIGNUP_PASSWORD = (By.XPATH, '//INPUT[@data-qaid="signup_password"]')
SIGNUP_REMEMBER_ME_CHECK = (By.XPATH, '//INPUT[@data-qaid="signup_remember_me_check"]')
SIGNUP_NEW_BTN = (By.XPATH, '//BUTTON[@data-qaid="signup_new_btn"]')
LOGIN_EMAIL = (By.XPATH, '//INPUT[@data-qaid="login_email"]')
LOGIN_PASSWORD = (By.XPATH, '//INPUT[@data-qaid="login_password"]')
LOGIN_REMEMBER_ME_CHECK = (By.XPATH, '//INPUT[@data-qaid="login_remember_me"]')
LOGIN_NEW_BTN = (By.XPATH, '//BUTTON[@data-qaid="login_new_btn"]')
LOGIN_SIGNUP_LINK = (By.XPATH, '//BUTTON[@data-qaid="sign_up"]')
CONTINUE_FACEBOOK_BTN = (By.XPATH, '//BUTTON[@data-qaid="continue_facebook_btn"]')
CONTINUE_GOOGLE_BTN = (By.XPATH, '//BUTTON[@data-qaid="continue_google_btn"]')
INCORRECT_EMAIL_OK_BTN = (By.XPATH, '//SPAN[text()="Darn! Your email or password is incorrect"]')
FORGOT_PASSWORD = (By.XPATH, '//BUTTON[@data-qaid="forgot_password"]')
FORGOT_PASSWORD_SEND_EMAIL_BTN = (By.XPATH, '//BUTTON[text()="Send email"]')
FORGOT_PASSWORD_TEXT = (By.XPATH, '//DIV[@class="promo__input Auth__email-input filled"]/input[@id="email"]')
FORGOT_PASSWORD_SENT = (By.XPATH, '//H3[text()="Request sent successfully"]')
AGREE_COOKIES_NEW_AUTH = (By.XPATH, '//BUTTON[@data-qaid="cookies_popup_button_agree"]')
LOGIN_PROCESS_ERROR = (By.XPATH, "//SPAN[@class='promo__input-message']")
NEW_EMPTY_FIELD_ERROR = (By.XPATH, "//SPAN[@class='promo__input-message']")
NEW_WRONG_CREDS_ERROR = \
    (By.XPATH, '//SPAN[@class="promo__input-message"][text()="The email or password you entered is incorrect"]')
REPUBLISH_BUTTON = (By.XPATH, '(//DIV[@data-qaid="dashboard_Republish"])[1]')

# Onboarding
ONBOARDING_CONTINUE_BTN = (By.XPATH, '//BUTTON[text()="Continue"]')
ONBOARDING_WEBSITE_INPUT = (By.XPATH, '//INPUT[@placeholder="Please enter your website URL"]')
ONBOARDING_BUSINESS_NAME = (By.XPATH, '//INPUT[@id="input-business-name"]')
ONBOARDING_BUSINESS_TYPE = (By.XPATH, '//INPUT[@placeholder="Select the industry that best describes your business"]')
ONBOARDING_BUSINESS_TYPE_1ST_OPTION = (By.XPATH, '//mark[@class="highlighted "]')
ONBOARDING_BUSINESS_TYPE_VALIDATION = (By.XPATH, '//INPUT[@value="Food"]')
ONBOARDING_COUNTRY_FIELD = (By.XPATH, '//DIV[@class="arrow"]')
ONBOARDING_COUNTRY_SELECTION_UK = (By.XPATH, '(//SPAN[@class="country-name"][normalize-space()="United Kingdom"])[1]')
ONBOARDING_COUNTRY_SELECTED_UK = (By.XPATH, '//DIV[@title="United Kingdom: + 44"]')
ONBOARDING_PHONE_NUMBER = (By.XPATH, '//INPUT[contains(@class, "form-control")]')
ONBOARDING_SPECIAL_OFFERS_CHECKBOX = (By.XPATH, '//DIV[@class="promo__checkbox onboarding-popup-step2__checkbox"]')
ONBOARDING_SPECIAL_OFFERS_CHECKED = (By.XPATH, '//DIV[@class="promo__checkbox onboarding-popup-step2__checkbox promo__checkbox--checked"]')
ONBOARDING_LOGO_EMPTY = (By.XPATH, '//DIV[@data-qaid="onboarding-popup-tile-view_empty"]')
ONBOARDING_LOGO_ADDED = (By.XPATH, '//DIV[@class="onboarding-popup-tile__box"]')
ONBOARDING_LOGO_ON_PREVIEW = (By.XPATH, '(//*[name()="image"])[1]')
ONBOARDING_PLACEHOLDER_LOGO_ON_PREVIEW = (By.XPATH, '//img[@alt="YOUR LOGO"]')
ONBOARDING_LOGO_MENU_DOTS = (By.XPATH, '//DIV[@data-qaid="onboarding-popup-tile_item_dots_menu"]')
ONBOARDING_LOGO_MENU_CROP = (By.XPATH, '//DIV[@data-qaid="onboarding-popup-option-menu_menu_crop"]')
ONBOARDING_LOGO_MENU_REPLACE = (By.XPATH, '//DIV[@data-qaid="onboarding-popup-option-menu_menu_replace"]')
ONBOARDING_LOGO_MENU_DELETE = (By.XPATH, '//DIV[@data-qaid="onboarding-popup-option-menu_menu_delete"]')
ONBOARDING_LOGO_CROP_POPUP_APPROVAL = (By.XPATH, '//BUTTON[@class="popup-btn popup-primary-btn bm-crop-btn"]')
ONBOARDING_LOGO_ADD = (By.XPATH, '//DIV[@data-qaid="onboarding-popup-tile-view_empty"]')
ONBOARDING_START_CREATING_BTN = (By.XPATH, '//BUTTON[text()="Start Creating"]')
ONBOARDING_2nd_SCREEN_TEXT = (By.XPATH, '//SPAN[@class="promo__typography onboarding-popup-step2__title-1 promo__typography--display promo__typography--micro promo__typography--left"]')

# Logged user
BILLING = (By.XPATH, '//DIV[@data-qaid="header_profile_menu_billing"][text()="Billing"]')
SIGN_OUT = (By.XPATH, '//DIV[@data-qaid="header_profile_menu_logout"][text()="Sign out"]')
SIGN_OUT_NEW = (By.XPATH, '(//*[@data-qaid="header_profile_menu_logout"])[1]')
NEW_PROJECT_BTN = (By.XPATH, '//SPAN[@data-qaid="new_project"]')
PROMO_SPECIAL = (By.XPATH, '//*[@id="switch_to_annual_button"]/span/span/span[1]')
CLAIM_OFFER = (By.XPATH, '//*[@id="switch_to_annual_button"]/span/span/span[2]')
MY_WORKSPACE_OR_VIDEOS = (By.XPATH, '//*[@data-qaid="header_dashboard"]')
MY_VIDEOS_DRAFTS = (By.XPATH, '//*[@data-qaid="header_dashboard_drafts"]')
MY_VIDEOS_PUBLISHED = (By.XPATH, '//*[@data-qaid="header_dashboard_published"]')
MY_VIDEOS_PTV = (By.XPATH, '//*[@data-qaid="header_photos_to_video"]')
MY_VIDEOS_BRANDS = (By.XPATH, '//*[@data-qaid="header_dashboard_brand_manager"]')
MY_VIDEOS_PLANNER = (By.XPATH, '//*[@data-qaid="header_dashboard_my-calendar"]')

# My account
INTERCOM_SURVEY_IFRAME = (By.XPATH, '//IFRAME[@name="intercom-banner-survey-frame"]')
INTERCOM_SURVEY_CLS = (By.XPATH, '//DIV[@data-testid="banner-survey-close-button"]')
MY_ACCOUNT = (By.XPATH, '//DIV[@data-qaid="header_profile_menu_settings"][text()="My account"]')
MY_ACCOUNT_TITLE = (By.XPATH, '//DIV[@class="settings-header"]')
MY_ACCOUNT_IFRAME = (By.XPATH, '//IFRAME[@id="settings-frame"]')
USER_NAME_H2 = (By.XPATH, '//DIV[@class="stg-user-info"]/h2')
USER_EMAIL_ACCOUNT = (By.XPATH, '//DIV[@class="stg-user-info"]/p[1]/strong')
CURRENT_PASS_INPUT = (By.XPATH, '//INPUT[@id="stg-current-password"]')
DELETE_ACCOUNT_PASS_INPUT = (By.XPATH, '//INPUT[@id="stg-current-password-delete"]')
DELETE_ACCOUNT_BTN = (By.XPATH, '//INPUT[@class="stg-delete-account"]')
DELETE_ACCOUNT_BTN_NEW = (By.XPATH, '//INPUT[@class="stg-delete-account-new"]')
DELETE_ACCOUNT_POPUP_BTN = (By.XPATH, '//*[@class="md-accept"]')
NEW_PASS_INPUT = (By.XPATH, '//INPUT[@id="stg-password"]')
RE_NEW_PASS_INPUT = (By.XPATH, '//INPUT[@id="stg-re-password"]')
POP_UP_OK = (By.XPATH, '//SPAN[@class="md-accept"][text()="OK"]')
ACCOUNT_SAVE_CHANGES_BTN = (By.XPATH, '(//INPUT[@class="stg-save-changes"])[2]')
SETTING_MESSAGE = (By.XPATH, '//DIV[@class="settings-message"]')
SETTING_MESSAGE_OK_BTN = (By.XPATH, '//DIV[@class="md-accept"]')
ERROR_POP_UP = (By.XPATH, '//H2[@class="md-title"][text()="Error"]')

# Search
SEARCH_INPUT_MAIN = (By.XPATH, '//INPUT[@data-qaid="library_search_input"]')
SEARCH_DROPDOWN = (By.XPATH, '//*[@data-qaid="library_search_dropdown"]')
SEARCH_PROMO_TEMPLATES = (By.XPATH, '//H2[@class="promo-collection-title"]')
SEARCH_PROMO_TEMPLATES2 = (By.XPATH, '(//H2[@class="create-page-test-h2"])[1]')
SEARCH_PROMO_VIDEOS = (By.XPATH, '//SPAN[@class="search-results-description"]/span[@class="results-for-keyword"]')
TEMPLATE = (By.XPATH, '(//DIV[@class="pr-overlay"])[1]')
RAW_VIDEO = (By.XPATH, '//*[text()="Start from scratch"]/following::div[@class="pr-overlay"][1]')
START_FROM_SCRATCH2 = (By.XPATH, '//*[text()="Start from scratch"]')
TEMPLATES_ARE_VISIBLE = (By.XPATH, '//div[@class="promo-collection-wrapper"]')
FOOTEGES_CONTAINER = (By.XPATH, '//DIV[@data-qaid="library_videos_container"]')
VIDEO = (By.XPATH, '//div[@class="pr-overlay"]')
RAW_VIDEOS_ARE_VISIBLE = (By.XPATH, '//SPAN[@class="results-for-keyword"]')
VIDEOS_ARE_VISIBLE = (By.XPATH, '//DIV[@class="search-filters-full"]')
SORTING_FILTER_OLD = (By.XPATH, '(//DIV[@class="drop-down-container"])[2]')
SORT_DROPDOWN_OLD = (By.XPATH, '(//DIV[@class="drop-down-item "])')
SORTING_FILTER = (By.XPATH, '(//span[@class="promo__dropdown__toggle-text"])[2]')
SORTING_FILTER2 = (By.XPATH, '(//span[@class="promo__dropdown__toggle-text"])[3]')
SORT_DROPDOWN = (By.XPATH, '(//DIV[@class="promo__dropdown__items"])[2]')
SORT_DROPDOWN2 = (By.XPATH, '(//DIV[@class="promo__dropdown__items"])')
SORT_DROPDOWN_TEXT = (By.XPATH, '//span[@class="promo__dropdown-item__text"]')
SORTING_OPTIONS = {
    'Most Popular': (By.XPATH, '//DIV[text()="Most Popular"]'),
    'Newest': (By.XPATH, '//DIV[text()="Newest"]'),
    'Best Match': (By.XPATH, '(//DIV[text()="Best Match"])[2]')
}

# Create  Page
MEDIA_UPLOAD_PHOTO_ON_CREATE = (By.XPATH, '//INPUT[@class="upload-photo-file"]')
ADD_PHOTO_TO_PROJECT_FROM_WIDGET = (By.XPATH, '//DIV[@class="widget-button "]')
UPLOADED_VIDEO_1ST = (By.XPATH, '//div[@class="video-content-section section-upload video-upload"]/div/div/div')
UPLOAD_VIDEO_TAB = (By.XPATH, '//div[@class="group"]/div[1]')
UPLOAD_PHOTOS_TAB = (By.XPATH, '//div[@class="group"]/div[2]')
UPLOADED_VIDEO_USE_BTN = (By.XPATH, '//div[@class="vu-results"]//button[@class="pr-overlay-btn pr-primary-btn pr-use-btn"][normalize-space()="Use"]')

# Templates
HEADER_TEMPLATES_BTN_OLD = (By.XPATH, '//*[@data-qaid="header_link_templates"]')
HEADER_TEMPLATES_BTN = (By.XPATH, '//*[@data-qaid="templates"]')
CUSTOMIZE_BTN = (By.XPATH, "//BUTTON[@data-qaid='library_video_item_customize_button'][text()='Customize']")
PREVIEW_BTN = (By.XPATH, "//BUTTON[@data-qaid='library_video_item_preview_button'][text()='Preview']")

# Social Media Calendar Page
HEADER_CALENDAR_BTN = (By.XPATH, '//A[@data-qaid="header_link_calendar"]')
CLASS_FOR_MONTH = (By.XPATH, '//DIV[@class="calendar-grid__item card  current-month"]')
CUSTOMIZE_TEMPLATE_FROM_CALENDAR = (By.XPATH, '//BUTTON[@class="btn promo-template-information__customize black"]')
NAV_NEXT = (By.XPATH, '//A[@class="calendar-header__nav-btn calendar-header__nav-btn--next"]')

# Preview
SHARE_BTN_ON_PREVIEW = (By.XPATH, '//BUTTON[normalize-space()="Share"]') # templates only
CUSTOMIZE_BTN_ON_PREVIEW = (By.XPATH, '//BUTTON[@class="btn-action"][text()="Customize"]') # templates only
PREVIEW_WRAPPER_WHOLE_VIDEO = (By.XPATH, '//div[@class="video-player-wrapper"]')
PREVIEW_RATIO_SQUARE = (By.XPATH, '//DIV[@data-ratio="square"]')
PREVIEW_RATIO_VERTICAL = (By.XPATH, '//DIV[@data-ratio="mobile"]')
PREVIEW_RATIO_WIDE = (By.XPATH, '//DIV[@data-ratio="wide"]')
PREVIEW_RATIO_SQUARE_SELECTED = (By.XPATH, '//DIV[@class="aspect square selected"]')
PREVIEW_RATIO_VERTICAL_SELECTED = (By.XPATH, '//DIV[@class="aspect vertical selected"]')
PREVIEW_RATIO_WIDE_SELECTED = (By.XPATH, '//DIV[@class="aspect wide selected"]')
PREVIEW_ARROW_NEXT = (By.XPATH, '//DIV[@class="btn-next-video btn-nav-video"]')
PREVIEW_ARROW_PREVIOUS = (By.XPATH, '//DIV[@class="btn-prev-video btn-nav-video"]')
PREVIEW_VIDEO_TITLE = (By.CLASS_NAME, 'video-title')
PREVIEW_VIDEO_TITLE_TEMPLATE = (By.XPATH, '//div[@class="video-title"][@style="display: block;"]')
PREVIEW_VIDEO_TITLE_RAW = (By.XPATH, '//div[@class="video-title"][normalize-space()="VIDEO PREVIEW"]')
PREVIEW_CLOSE_VIDEO = (By.CLASS_NAME, 'btn-close-video')
PREVIEW_SHARE_BTN_SMALL = (By.XPATH, '//BUTTON[@class="share-btn share-btn-small"]')
PREVIEW_SHARE_BTN_BIG = (By.XPATH, '//BUTTON[@class="share-btn share-btn-big"]')
SHARE_POPUP = (By.XPATH, '//DIV[@class="share-popup"]')
PREVIEW_CUSTOMIZE_BTN = (By.XPATH, '//BUTTON[@class="btn-action"][text()="Customize"]')
USE_BTN = (By.XPATH, '(//BUTTON[@data-qaid="library_video_item_use_button"])')
PREVIEW_USE_BTN = (By.XPATH, '//BUTTON[@class="btn-action"][normalize-space()="Use"]') # raw videos only
PREVIEW_RAW_PLAY_PAUSE_BTN_PLAY = (By.XPATH, '//div[@class="play-pause-btn play"]')
PREVIEW_RAW_PLAY_PAUSE_BTN_PAUSE = (By.XPATH, '//div[@class="play-pause-btn pause"]')
PREVIEW_TEMPLATE_TIME_DISPLAY = (By.XPATH, '(//div[@class="time-display"])[1]')
PREVIEW_RAW_TIME_DISPLAY = (By.XPATH, '(//div[@class="time-display"])[2]')


# Editor
SAVE_AND_PREVIEW_BTN = (By.XPATH, "//DIV[@data-qaid='editor_save_and_preview_button']")
MODES_EDITOR = (By.XPATH, '//LI[@data-qaid="modes_editor"]')
EDITOR_TAB = (By.XPATH, '//LI[@data-qaid="modes_editor"]')
MEDIA_TAB = (By.XPATH, '//LI[@data-qaid="modes_media"]')
MUSIC_TAB = (By.XPATH, '//LI[@data-qaid="modes_music"]')
ADD_WATERMARK = (By.XPATH, '//*[@id="watermark-wrapper"]/div')
ADD_WATERMARK_NOT_EMPTY = (By.XPATH, '//G[@id="ic_watermark-"]')
NEXT_LEVEL_PLANS_BTN = (By.XPATH, '//BUTTON[@class="see-plans"]')
AUDIO_REPLACED_POPUP = (By.XPATH, '//DIV[@class="title"][text()="Audio Track Was Replaced"]')
AUDIO_REPLACED_OK_BTN = (By.XPATH, '//BUTTON[@class="ok-button"]')
ONBOARDING_APPCUES_FRAME = (By.XPATH, '//IFRAME[@class="appcues-tooltip-container align-right"]')
ONBOARDING_APPCUES_HIDE = (By.XPATH, '//*[@class="text-muted appcues-skip"]')
DELETE_WATERMARK = (By.XPATH, '//BUTTON[@data-qaid="editor_delete_watermark"]')
DELETE_WATERMARK_CONFIRM = \
    (By.XPATH, '//BUTTON[contains(@class, "popup-btn popup-primary-btn") and text()="Delete"]')
CLICK_ADD_BUTTON = (By.XPATH, '//BUTTON[@class="add-button-menu with-playbutton"]')
CAPTION_OPTION = (By.XPATH, '//LI[@class="flyout-menu-item add-caption menu-item-addCaption"]')
CAPTION_TIMING_POPUP = (By.XPATH, '//DIV[@class="title"][text()="Caption Timing"]')
CAPTION_POPUP_OK_BTN = (By.XPATH, '//BUTTON[@class="ok-button"]')
CAPTION_WRAPPER = (By.XPATH, '//DIV[@class="caption-wrapper"]')
HOVER_CAPTION = (By.XPATH, '//DIV[@class="overlay-button"]')
SECOND_CAPTION = (By.XPATH, '(//DIV[@class="inner-caption-wrapper"])[2]')
DELETE_CAPTION = (By.XPATH, '//LI[@class="flyout-menu-item delete-caption menu-item-duplicate"]')
DISCARD_BUTTON = (By.XPATH, '//BUTTON[@data-qaid="editor_discard_button"]')
DISCARD_BUTTON_DISABLED = (By.XPATH, '//BUTTON[@data-qaid="editor_discard_button"][@disabled=""]')
DISCARD_BUTTON_ENABLED = (By.XPATH, '//BUTTON[@data-qaid="editor_discard_button"][@class="discard-button enable enabled"]')
YES_DISCARD_BTN_ON_POP_UP = (By.XPATH, "//button[normalize-space()='Yes, discard']")
FIRST_CAPTION = (By.XPATH, '(//DIV[@class="inner-caption-wrapper"])[1]')
CHOOSE_CAPTION_ON_TIMELINE = (By.XPATH, '(//div[@class="caption-overlay"])[1]')
EDITOR_CUSTOMIZE_BAR = (By.XPATH, '//div[@class="customize-bar-container"]')
TIMELINE_HANDLE_RIGHT = (By.XPATH, '(//DIV[@class="timeline-item-resize-handle handle-right"])[3]')
TIMELINE_HANDLE_RIGHT_15_SECS = (By.XPATH, '//*[@class="show"][text()=15]')
PLAY_BUTTON = (By.XPATH, '//BUTTON[@class="play"]')
PAUSE_BUTTON = (By.XPATH, '//BUTTON[@class="play playing"]')
HOVER_TIMELINE = (By.XPATH, '//DIV[@class="inner-clip-wrapper"]')
HOVER_TIMELINE_2 = (By.XPATH, '(//DIV[@class="inner-clip-wrapper"])[2]')
EDIT_BUTTON = (By.XPATH, '(//BUTTON[@class="clip-edit-menu-button show-clip-edit-menu-button"])[0]')
DUPLICATE_CLIP = (By.XPATH, '(//LI[@class="flyout-menu-item duplicate-clip menu-item-duplicate"])')
REPLACE_CLIP = (By.XPATH, '(//LI[@class="flyout-menu-item replace-clip menu-item-replace"])')
SORTING_FILTER_3 = (By.XPATH, '(//SPAN[@class="promo__dropdown__toggle-text"][text()="Videos"])')
PHOTOS_FILTER = (By.XPATH, '(//SPAN[@class="promo__dropdown-item__text"][text()="Photos"])')
TRIM_VIDEO = (By.XPATH, '(//LI[@class="flyout-menu-item trim-clip menu-item-trim"])')
DURATION = (By.XPATH, '(//DIV[@class="time-display"])[2]')
EDIT_PHOTO = (By.XPATH, '(//LI[@class="flyout-menu-item edit-photo-clip menu-item-editPhoto"])')
CLICK_APPLY = (By.XPATH, '(//BUTTON[@class"big-button primary apply"])')
EDIT_PHOTO_ZOOM_IN = (By.XPATH, '//div[@class="controls--main"]//button[2]//img[1]')
EDIT_PHOTO_DONE_BTN = (By.XPATH, '//BUTTON[@class="button blue"]')

# Editor characters
TEXT_ANIMATION = (By.XPATH, '//DIV[@class="text-style-el react-draggable"]')
TEXT_ANIMATION_BOX = (By.XPATH, '//DIV[@class="animation-el"]')
TEXT_ANIMATION_EDIT_BOX = (By.XPATH, '//DIV[@class="text-style-component edit-mode"]//DIV[@class="input"]')
TEXT_ANIMATION_EDIT_BOX_DONE = (By.XPATH, '//DIV[text()="Done"]')
TEXT_ANIMATION_TEXT_BOX = (By.XPATH, '(//*[text()="PROMO TESTING"])[2]')

# Editor - ratios
SELECTED_RATIO = (By.XPATH, '//DIV[@data-for="ratios"]')
RATIO_SQUARE = (By.XPATH, '//DIV[@data-value="square"]')
RATIO_WIDE = (By.XPATH, '//DIV[@data-value="wide"]')
RATIO_VERTICAL = (By.XPATH, '//DIV[@data-value="vertical"]')
RATIO_GOT_IT_BTN = (By.XPATH, '//BUTTON[@class="ok-button"]')
RATIO_THANKS_BTN = (By.XPATH, '//BUTTON[@class="cancel-button"]')
RATIO_TOOLBAR = (By.XPATH, '//DIV[@data-qaid="editor_toolbar_ratios_menu"]')

# Editor - font color
COLOR_PICKER = (By.XPATH, '//BUTTON[@data-qaid="editor_text_color"]')
YELLOW_COLOR = (By.XPATH, '//DIV[@style="background-color: rgb(255, 214, 68);"]')
PICK_THE_COLOR = (By.XPATH, '//DIV[@class="contour"]')
COLOR_TAB_TEXT = (By.XPATH, '//DIV[@data-qaid="editor_text_color_tabs"]/span[1]')
COLOR_TAB_BACKGROUND = (By.XPATH, '//DIV[@data-qaid="editor_text_color_tabs"]/span[2]')
RGBA_INPUT = (By.XPATH, '//INPUT[contains(@id, "rc-editable-input")]')
CAPTION_IN_EDITOR = (By.XPATH, '//DIV[@class="animation-el"]/span/svg/g/g/text/tspan')
EDIT_COLOR_TXTBOX = (By.XPATH, '//DIV[@data-qaid="editor_color_picker_input"]/div/input')
EDITOR_PANE = (By.XPATH, '//DIV[@class="content-pane customize-decor"]')
EDITOR_TEXT_COLOR = (By.XPATH, '//*[@aria-label="PROMO TESTING"]')
EDITOR_TEXT_COLOR2 = (By.XPATH, '(//*[@fill="rgb(117,38,38)"])[1]')
TEXT_COLOR_BG = (By.XPATH, '//DIV[@data-qaid="editor_text_color_tabs"]/span[text()="Background"]')
EDITOR_TEXT_COLOR_BG = (By.XPATH, '//*[@fill="rgb(203,92,208)"]')
EDITOR_TEXT_COLOR_BG2 = (By.XPATH, '//DIV[@class="contour"]')

# Editor - fonts
FONTS_DROPDOWN = (By.XPATH, '//DIV[@data-qaid="editor_dropdown_fonts"]')
AMATIC_FONT = (By.XPATH, '//DIV[@style="font-family: "Amatica SC"; font-weight: 400;"]')
LOBSTER_FONT = (By.XPATH, '//DIV[@style="font-family: Lobster; font-weight: 400;"]')
SEARCH_FONT_INPUT = (By.XPATH, '//INPUT[@data-qaid="bm_search_input"]')
SEARCH_EMPTY_INPUT = (By.XPATH, '//DIV[@class="bm-search-input bm-search-input--empty"]')
CLEAR_SEARCH_MY_FONTS = (By.XPATH, '//div[@class="bm-search-input__clear"]')
MY_FONTS_BTN = (By.XPATH, '//*[text()="My fonts"]')
ADD_FONTS_BTN = (By.XPATH, '//*[text()="Add Font"]')
FROM_COMPUTER_FONT = (By.XPATH, '//DIV[@data-qaid="editor_dropdown_fonts"]/../../input')
FROM_GOOGLE_FONT = (By.XPATH, '//DIV[@class="bm-font-selector__add-font-button-option bm-font-selector__add-font-button-option--google"]')
GOOGLE_CHOSEN_FONT = (By.XPATH, '//div[@class="bm-font-sample bm-multi-select-fonts-list__font-sample"]')
GOOGLE_ALREADY_CHOSEN_FONT = (By.XPATH, '//div[@class="bm-multi-select-fonts-list__list-item bm-multi-select-fonts-list__list-item--disabled"]')
GOOGLE_FONT_ADD_BUTTON = (By.XPATH, '(//button[normalize-space()="Add"])[1]')
GOOGLE_SEARCH_FONT_INPUT_POPUP = (By.XPATH, '(//INPUT[@data-qaid="bm_search_input"])[1]')
GOOGLE_SEARCH_FONT_INPUT_DROPDOWN = (By.XPATH, '//div[@class="bm-search-input bm-search-input--empty"]//input[@placeholder="Search font"]')
GOOGLE_PRIDI_FONT_CHOSEN = (By.XPATH, '//div[@class="bm-font-sample bm-font-selector__font-sample"][normalize-space()="Pridi"]')
GOOGLE_PRIDI_BOLD_CHOOSE = (By.XPATH, '//div[@class="bm-font-sample bm-font-selector__font-sample"][normalize-space()="Pridi Bold"]')
CUSTOM_FONT_NO_RESULTS = (By.XPATH, '//div[@class="bm-font-selector__no-results"]')
GOOGLE_FONT_CANCEL = (By.XPATH, '(//button[normalize-space()="Cancel"])[1]')
FONT_UPLOAD_CHECKBOX = (By.XPATH, '//DIV[@class="promo-checkbox unchecked"]')
FONT_UPLOAD_BTN = (By.XPATH, '//BUTTON[@class="popup-btn popup-primary-btn"][text()="Upload"]')
FONT_UPLOAD_DONE_BTN = (By.XPATH, '//BUTTON[@class="bm-popup__button bm-popup__button--blue"]')
UPLOADED_FONT_SEL = (By.XPATH, '//*[text()="JackSimbaPersonalUse"]')

# Editor - background
COLOR_OF_BACKGROUND = (By.XPATH, '//BUTTON[@data-qaid="editor_clip_filter"]')

# Editor logo and watermark
EDITOR_WATERMARK_FILLED = (By.XPATH, '//DIV[@data-qaid="add_watermark"]')
EDITOR_WATERMARK = (By.XPATH, '//DIV[@class="editor-watermark-placeholder"]')
EDITOR_WATERMARK_POSITION = (By.XPATH, '//BUTTON[@data-qaid="editor_watermark_position"]')
EDITOR_WATERMARK_OPACITY = (By.XPATH, '//BUTTON[@data-qaid="editor_watermark_opacity"]')
EDITOR_WATERMARK_SATURATION = (By.XPATH, '//BUTTON[@data-qaid="editor_watermark_saturation"]')
UPLOAD_LOGO = (By.XPATH, '(//DIV[@class="add-creative-image-box creative-box"]/following::input[@type="file"])[1]')
ADD_TO_VIDEO_BTN = (By.XPATH, '//BUTTON[text()="Add to Video"]')
UPLOADED_LOGOS = (By.XPATH, '//DIV[@class="creative-item"]')
UPLOADED_LOGOS_HOV = (By.XPATH, '//DIV[@class="creative-item-overlay"]')
UPLOADED_LOGOS_DEL = (By.XPATH, '//DIV[@class="creative-item-btn icon-delete-dash"]')
OUTRO_BTN = (By.XPATH, '//*[text()="OUTRO"]')

# Logo in Editor
EDITOR_LOGO_ADD_LOGO = (By.XPATH, '//div[normalize-space()="Add Logo"]')
EDITOR_LOGO_IMAGE = (By.XPATH, '//DIV[@class="logo-image"]')
EDITOR_LOGO_DRAGGING_AREA = (By.XPATH, '//DIV[@class="dragging-area"]')
EDITOR_LOGO_UPLOAD_INPUT = (By.XPATH, '//INPUT[@accept="image/jpg, image/png, image/gif, image/jpeg"]')
EDITOR_LOGO = (By.XPATH, '//DIV[@class="item ui-draggable ui-draggable-handle ui-draggable-disabled logo-placeholder"]')
EDITOR_LOGO_POSITION = (By.XPATH, '//BUTTON[@data-qaid="editor_logo_position"]')
EDITOR_LOGO_REMOVE = (By.XPATH, '//BUTTON[@data-qaid="editor_remove_logo"]')
EDITOR_UPLOAD_LOGO = (By.XPATH, '//BUTTON[@data-qaid="editor_upload_logo"]')
EDITOR_WATERMARK_PRICING_POPUP = (By.XPATH, '//*[text()="Brand Videos With A Watermark"]')
BM_PRICING_POPUP = (By.XPATH, '//*[text()="Create and Manage Your Brands"]')

# Editor -  alignment
ALIGN_LEFT = (By.XPATH, '//BUTTON[@data-qaid="editor_text_align_left"]')
ALIGN_CENTER = (By.XPATH, '//BUTTON[@data-qaid="editor_text_align_center"]')
ALIGN_RIGHT = (By.XPATH, '//BUTTON[@data-qaid="editor_text_align_right"]')
ALIGN_CENTER_NEW_2 = (By.XPATH, '//BUTTON[@data-qaid="editor_text_align_center"]')
ALIGN_RIGHT_NEW_2 = (By.XPATH, '//BUTTON[@data-qaid="editor_text_align_right"]')

# Editor - text position and styles
TEXT_POSITION_BTN = (By.XPATH, '//BUTTON[@data-qaid="editor_text_position"]')
TEXT_POSITIONS_CHANGE_BTN = (By.XPATH, '(//DIV[@class="btn push-in-trans"])')
TEXT_STYLES_BTNS = (By.XPATH, '(//DIV[@class="text-style-option-template"])')
TEXT_STYLES_BTN = (By.XPATH, '(//DIV[@class="text-style-option-template"])[3]')
TEXT_STYLES_SELECTED = (By.XPATH, '(//DIV[@class="text-style-option-template selected"])')
CLIP_LOTTIE = (By.XPATH, '//DIV[@class="item lottie"]')
REPLACE_TEXT_STYLE = (By.XPATH, '//BUTTON[@class="popup-btn popup-primary-btn"]')

# Editor -  capitalize
CAPITALIZE_MAIN_ICON = (By.XPATH, '//BUTTON[@data-qaid="editor_text_format"]')
UPPERCASE_ICON_NEW = (By.XPATH, '(//div[@class="icon"])[1]')
CAPITALIZED_ICON_NEW = (By.XPATH, '(//div[@class="icon"])[2]')
LOWERCASE_ICON_NEW = (By.XPATH, '//div[@class="icon lowercase"]')

# Editor - Outro
OUTRO_BACKGROUND_COLOR = (By.XPATH, '//button[@data-qaid="editor_outro_background_color"]')
OUTRO_UPLOAD_BACKGROUND = (By.XPATH, '//button[@class="widget-upload-selector dz-clickable"]')
OUTRO_REMOVE_BACKGROUND = (By.XPATH, '//button[@data-qaid="editor_remove_outro_background"]')
OUTRO_ON_TIMELINE = (By.XPATH, '(//DIV[normalize-space()="OUTRO"])[1]')
OUTRO_SELECTED_COLOR = (By.XPATH, '(//div[@class="contour"])[11]')

# Editor my Brands
MY_BRANDS_CTA = (By.XPATH, '//DIV[@data-qaid="editor_my_brands"]')
SELECT_BRAND = (By.XPATH, '//DIV[@class="sidebar__brands-brand-box"]')
MANAGE_BRANDS_CTA = (By.XPATH, '//BUTTON[@class="sidebar__brands-button--manage"]')
MANAGE_BRAND_CONF = (By.XPATH, '//BUTTON[@class="bm-popup__button bm-popup__button--blue add-brand"]')
EDITOR_WATERMARK_IMAGE = (By.XPATH, '//DIV[@class="editor-watermark-resize react-draggable"]')
EDITOR_WATERMARK_IMAGE_AGAIN = \
    (By.XPATH, '//DIV[@class="editor-watermark-resize react-draggable react-draggable-dragged"]')
UPLOAD_IMAGE = (By.XPATH, '//INPUT[@accept="image/jpg, image/png, image/gif, image/jpeg"]')
CROSS_BTN = (By.XPATH, '//DIV[@class="close-btn"]')
SELECT_OUTROS = (By.XPATH, '(//DIV[@class="text-style-option-template outro"])')
LOGO_EDITOR_BTN = (By.XPATH, '//I[@class="upload-logo"]')
IMAGE_DONE_BTN = (By.XPATH, '//BUTTON[@class="popup-btn popup-primary-btn done-btn"]')
ADD_BRAND_EDITOR = (By.XPATH, '//BUTTON[@class="sidebar__brands-button"]')
CREATE_BRAND_EDITOR = (By.XPATH, '//BUTTON[@class="bm-popup__button bm-popup__button--blue add-brand"]')
APPLY_BRAND_POP_UP = (By.XPATH, '//*[@class="popup-content-inner"]')
APPLY_BRAND_POP_UP_CTN_BTN = (By.XPATH, '//BUTTON[text()="Continue"]')

# Editor Media Tab
MEDIA_LIBRARY_TAB = (By.XPATH, '//DIV[@data-qaid="media_library_tab"]')
MEDIA_UPLOADS_TAB = (By.XPATH, '//DIV[@data-qaid="media_upload_tab"]')
MEDIA_FAVORITES_TAB = (By.XPATH, '//DIV[@data-qaid="media_favorites_tab"]')
MEDIA_UPLOAD_BTN = (By.XPATH, '//DIV[@data-qaid="upload_btn"]')
MEDIA_UPLOAD_VIDEO = (By.XPATH, '//DIV[@data-qaid="upload_video"]')
MEDIA_UPLOAD_VIDEO2 = (By.XPATH, '//INPUT[@class="upload-video-file"]')
MEDIA_UPLOAD_PHOTO = (By.XPATH, '//INPUT[@data-qaid="upload_photo"]')
UPLOAD_IN_PROGRESS_POPUP = (By.XPATH, '//DIV[@class="alert-popup"]')
UPLOAD_TITLE_ON_POPUP = (By.XPATH, '//DIV[@class="alert-popup"]/div[1]')
MEDIA_SEARCH_INPUT = (By.XPATH, '//INPUT[@data-qaid="library_search_input"]')
MEDIA_SEARCH_FILTER = (By.XPATH, '//DIV[@data-qaid="media_search_filter"]')
PHOTOS_MEDIA_SEARCH_FILTER = (By.XPATH, 'data-qaid="media_search_photo_filter"')
ALL_MEDIA_FILTER = (By.XPATH, '(//DIV[@class="drop-down-container"])[1]')
ALL_MEDIA_FILTER_NEW = (By.XPATH, '(//span[@class="promo__dropdown__toggle-text"][text()="All Media"])[1]')
EDITORIAL_MEDIA_FILTER_NEW = (By.XPATH, '(//span[@class="promo__dropdown__toggle-text"][text()="Editorial"])[1]')
PHOTOS_ALL_MEDIA_FILTER = (By.XPATH, '//DIV[@class="dropdown-component photo-type-dropdown"]')
PHOTOS_ALL_MEDIA_FILTER_NEW = (By.XPATH, '(//span[@class="promo__dropdown__toggle-text"][text()="All Media"])[2]')
PREMIUM_FILTER = (By.XPATH, '//DIV[@class="drop-down-item "][text()="Premium"]')
PREMIUM_FILTER_NEW = (By.XPATH, '(//span[@class="promo__dropdown-item__text"][text()="Premium"])[2]')
EDITORIAL_FILTER = (By.XPATH, '(//DIV[@class="drop-down-item "][text()="Editorial"])[1]')
PHOTOS_EDITORIAL_FILTER = (By.XPATH, '(//DIV[@class="drop-down-item "][text()="Editorial"])[2]')
FILTERED_VIDEOS = (By.XPATH, '//DIV[@data-qaid="library_video_item"]')
FILTERED_PHOTOS = (By.XPATH, '//SECTION[@class="main-photo-box flex-image-item"]')
PREMIUM_TAGS = (By.XPATH, '//DIV[@class="cost-badge bottom premium-badge static"][text()="Premium"]')
EDITORIAL_TAGS = (By.XPATH, '//DIV[@class="cost-badge bottom editorial-badge static"][text()="Editorial"]')
PHOTOS_EDITORIAL_TAGS = (By.XPATH, '//DIV[@class="photo-box__badge"][text()="Editorial"]')
CHOSEN_VIDEO = (By.XPATH, '(//DIV[@class="pr-overlay"])')
CHOSEN_VIDEO_TO_FAV = (By.XPATH, '(//DIV[@data-qaid="library_video_item"])[3]/div[3]')
ADD_FAVOURITES = (By.XPATH, '(//A[@title="Add to Favorites"])[3]')
REMOVE_FAVOURITES = (By.XPATH, '(//A[@title="Remove from Favorites"])[1]')
FAVOURITE_SELECTED = (By.XPATH, '(//A[@title="Remove from Favorites"])[1]')
IS_VIDEO_ADDED = (By.XPATH, '//DIV[@class="clip selected is-gradient react-draggable"]')
UPLOAD_COMPLETED_WIDGET = (By.XPATH, '//DIV[@class="widget-main-text"][text()="Upload Completed"]')
UPLOAD_COMPLETED_WIDGET_CLOSE = (By.XPATH, '//DIV[@class="close-widget-widget-notification show"]')
ADD_TO_PROJECT_WIDGET_BTN = (By.XPATH, '//[@class="widget-button"]')
ADD_VIDEO_TO_PROJECT_BTN = (By.XPATH, '(//BUTTON[@data-qaid="library_video_item_use_button"])[1]')
VIDEO_ADDED_IN_TEMPLATE = (By.XPATH, '//DIV[@class="clip-edit-wrapper show-clip-overlay"]')
UPLOADS_FIRST_VIDEO = (By.XPATH, '(//DIV[@class="pr-video-preview-wrap "])[1]')
UPLOADS_FIRST_PHOTO = (By.XPATH, '//SECTION[@class="photo-list-center clearfix"]/section[1]')
UPLOADS_DELETE_ICON = (By.XPATH, '//DIV[@class="photo-box"]/div[3]')
UPLOADS_POPUP_DELETE = (By.XPATH, '//BUTTON[@class="popup-btn popup-primary-btn"][text()="Delete"]')
UPLOAD_VIDEO_DELETE = (By.XPATH, '(//DIV[@class="delete-icon"])[1]')
TRANSITION_BTN = (By.XPATH, '(//DIV[@class="transition-btn"])[1]')
TRANSITION_BTN2 = (By.XPATH, '(//DIV[@class="transition-btn"])[2]')
TRANSITION_BTN4 = (By.XPATH, '(//DIV[@class="transition-btn"])[4]')
ADD_PHOTO_TO_PROJECT = (By.XPATH, '(//DIV[@class="show add-button"])[1]')
NONE_TRANSITION = (By.XPATH, '//li[@class="flyout-menu-item none  menu-item-cut"]')
ADDED_MEDIA_EDIT_BUTTON = (By.XPATH, '(//BUTTON[@class="clip-edit-menu-button show-clip-edit-menu-button"])[3]')
ADDED_MEDIA = (By.XPATH, '(//DIV[@class="inner-clip-wrapper"])[3]')
ADDED_MEDIA_REPLACE_BTN = (By.XPATH, '//LI[@class="flyout-menu-item replace-clip menu-item-replace"]')
REPLACE_MEDIA_BTN = (By.XPATH, '(//DIV[@class="show add-button"])[3]')
LIB_PIC_HOV = (By.XPATH, '(//DIV[@class="photo-box"])[3]')
ADDED_MEDIA_SELECTED = (By.XPATH, '//DIV[@class="clip showing-clip-overlay selected is-gradient"]')
PHOTOS_VIDEOS_HOVER = (By.XPATH, '//DIV[@class="selected-item-container"]')
SELECT_PHOTOS_CAT = (By.XPATH, '//DIV[@class="dropdown-item-name"][text()="Photos"]')
SELECT_VIDEOS_CAT = (By.XPATH, '//DIV[@class="dropdown-item-name"][text()="Videos"]')
MUSIC_LIBRARY_2ND_AUDIO = (By.XPATH, '(//div[@class="music-item playable-item fadeInOnHover loaded"])[1]')

VIDEOS_PHOTOS_DROPDOWN_OLD = (By.XPATH, '//*[@data-qaid="library_search_dropdown"]')
DROPDOWN_SELECT_VIDEOS_OLD = (By.XPATH, '//DIV[@data-qaid="library_search_dropdown_videos"]')
DROPDOWN_SELECT_PHOTOS_OLD = (By.XPATH, '//DIV[@data-qaid="library_search_dropdown_photos"]')
VIDEOS_PHOTOS_DROPDOWN = (By.XPATH, '//DIV[@class="promo__dropdown library-search-dropdown"]')
DROPDOWN_SELECT_VIDEOS = (By.XPATH, '//DIV[@class="promo__dropdown__items"]/div')
DROPDOWN_SELECT_PHOTOS = (By.XPATH, '//DIV[@class="promo__dropdown__items"]/div[2]')
PHOTO_HOVERED = (By.XPATH, '(//DIV[@class="photo-box"])[2]')
SELECT_PHOTO_CIRCLE = (By.XPATH, '(//DIV[@class="select-photo-icon circle-icon"])[2]')
ZOOM_PHOTO_ICON = (By.XPATH, '(//DIV[@class="zoom-preview-button "])[2]')
ADD_PHOTO_TO_PROJECT_FROM_BAR = (By.XPATH, '//DIV[@class="add-to-project-button"]')
CLOSE_PHOTO_PREVIEW = (By.XPATH, '//IMG[@class="close"]')
ADD_PHOTO_FROM_PREVIEW = (By.XPATH, '//DIV[@class="add-button:][text()="USE"]')
NAV_LEFT_PHOTO_PREVIEW = (By.XPATH, '//DIV[@class="nav nav-left"]')
NAV_RIGHT_PHOTO_PREVIEW = (By.XPATH, '//DIV[@class="nav nav-right"]')

TRANSITIONS = {
    'FADE_TRANSITION': (By.XPATH, '//DIV[@class="flyout-menu"]/ul/li[text()="Fade"]'),
    'TRIO_TRANSITION': (By.XPATH, '//DIV[@class="flyout-menu"]/ul/li[text()="Trio"]'),
    'MIDFIELD_TRANSITION': (By.XPATH, '//DIV[@class="flyout-menu"]/ul/li[text()="Midfield"]'),
    'TOPDOWN_TRANSITION': (By.XPATH, '//DIV[@class="flyout-menu"]/ul/li[text()="Top Down"]'),
    'GLIDE_TRANSITION': (By.XPATH, '//DIV[@class="flyout-menu"]/ul/li[text()="Glide"]'),
    'PUZZLE_TRANSITION': (By.XPATH, '//DIV[@class="flyout-menu"]/ul/li[text()="Puzzle"]'),
    'PATIO_TRANSITION': (By.XPATH, '//DIV[@class="flyout-menu"]/ul/li[text()="Patio"]')
}

# Editor Music Tab
MUSIC_LIBRARY_TAB = (By.XPATH, '//DIV[@data-qaid="music_library_tab"]')
MUSIC_UPLOADS_TAB = (By.XPATH, '//DIV[@data-qaid="music_upload_tab"]')
MUSIC_FAVORITES_TAB = (By.XPATH, '//DIV[@data-qaid="music_favorites_tab"]')
MUSIC_LIBRARY_TAB_SELECTED = (By.XPATH, '//DIV[@class="nav-item mh-library selected"]')
MUSIC_SEARCH = \
    (By.XPATH, '//INPUT[@data-qaid="library_search_input"][@placeholder="Search for music (by title and composer)"]')
CHOOSE_TRACK_BTN = (By.XPATH, '(//DIV[@class="choose choose--blue"][text()="Use Track"])[1]')
CHOOSE_2ND_TRACK_BTN = (By.XPATH, '(//DIV[@class="choose choose--blue"][text()="Use Track"])[2]')
MUSIC_FAVORITE_ICON = (By.XPATH, '//A[@title="Add to Favorites"]')
USE_BTN_ON_PREVIEW = (By.XPATH, '//BUTTON[@class="btn-action"][text()="Use"]')
AUDIO_UPLOAD = (By.XPATH, '//INPUT[@class="upload-audio-file"]')
AUDIO_DELETE_ICON = (By.XPATH, '(//DIV[@class="delete-icon"])[1]')
MUSIC_DROPDOWN = (By.XPATH, '(//SPAN[@class="button__title--clone"])')
GENRE_DROPDOWN = (By.XPATH, '//SPAN[@class="button__title--clone"][text()="Genre"]')
MOOD_DROPDOWN = (By.XPATH, '//SPAN[@class="button__title--clone"][text()="Mood"]')
TEMPO_DROPDOWN = (By.XPATH, '//SPAN[@class="button__title--clone"][text()="Tempo"]')
INSTRUMENT_DROPDOWN = (By.XPATH, '//SPAN[@class="button__title--clone"][text()="Instrument"]')
SUB_CAT_BIG_BAND = (By.XPATH, '//SPAN[text()="Big band"]/..')
SUB_CAT_ACTION = (By.XPATH, '//SPAN[text()="Action"]/..')
SUB_CAT_MEDIUM = (By.XPATH, '//SPAN[text()="Medium (80-120 BPM)"]/..')
SUB_CAT_DRUM = (By.XPATH, '//SPAN[text()="Drums"]/..')
SUB_CAT_CLEAR_BTN = (By.XPATH, '(//SPAN[@class="button__icon--clear"])')
MUSIC_SUB_CAT = (By.XPATH, '(//LI[@class="menu__item"])')
USE_TRACK_BTN = (By.XPATH, '(//DIV[@class="choose choose--blue"])[2]')
HOVER_MUSIC = (By.XPATH, '(//DIV[@class="music-item playable-item fadeInOnHover loaded"])[2]')
MUSIC_AUDIO_GRID = (By.XPATH, '//DIV[@class="bg"]')
HOVER_MUSIC_BG_1 = (By.XPATH, '(//DIV[@class="bg"])[2]')
HOVER_MUSIC_BG_2 = (By.XPATH, '(//DIV[@class="title title--center"])[2]')
HOVER_MUSIC_NICE = (By.XPATH, '//DIV[@title="So Nice"]')
SAMPLE_AUDIO = (By.XPATH, '//*[text()="sample.mp3"]')
UPLOADED_AUDIO = (By.XPATH, '//DIV[text()="sample.mp3"]/../..')
DELETE_UPLOADED_MUSIC = (By.XPATH, '//DIV[text()="sample.mp3"]/../../div[1]')
DELETE_TRACK_CONFIRM = (By.XPATH, '//BUTTON[@class="popup-btn popup-primary-btn"][text()="Delete"]')
TRIM_TRACK_BTN = ()  # to be added as qaid
HOVER_UPLOADED_MUSIC = (By.XPATH, '//DIV[@class="main-title"][@title="sample.mp3"]')
TRIM_TRACK_INDICATOR_START = (By.XPATH, '//DIV[@class="ta-time-indicator ta-start-time"]')
TRIM_TRACK_INDICATOR_END = (By.XPATH, '//DIV[@class="ta-time-indicator ta-end-time"]')
TRIM_CANCEL_BTN = (By.XPATH, '//button[normalize-space()="Cancel"]')

# Publishing
PUBLISH_BTN = (By.XPATH, "//DIV[@class='publish-button btn tippy']")
PUBLISH_BTN_NEW = (By.XPATH, '//DIV[@class="publish-button publish-button-new btn tippy"]')
PRICING_TEXT = (By.XPATH, "//*[@class='center-title']")
VIDEO_IS_READY_CONTINUE_BTN = (By.XPATH, "//DIV[@class='download-button show fade-in'][text()='Continue']")
EDITORIAL_VIDEO_IS_READY_CONTINUE_BTN = (By.XPATH, '//BUTTON[text()="Continue"]')
EDITORIAL_PUBLISH_CHECKBOX = (By.CSS_SELECTOR, '.promo__checkbox__label')
PREMIUM_CLIP_TEXT = (By.XPATH, '//SPAN[text()="This video has 1 premium clip"]')
EDITORIAL_NON_COMMER_TXT = (By.XPATH, '//SPAN[text()="Editorial media for non-commercial use"]')
EDITORIAL_UPGRADE_NOW_BTN = (By.XPATH, '//BUTTON[text()="Upgrade now"]')
EDITORIAL_UPGRADE_BUSINESS_PLAN = (By.XPATH, '(//DIV[@class="upgrade force-blue"])[2]')
PUBLISH_READY = (By.XPATH, '//*[text()="Your video is ready to be published"]')
VID_PUBLISH_READY = (By.XPATH, '//DIV[@class="pp-text-1"][text()="Your video is ready!"]')
NPP_TITLE_READY = (By.XPATH, '//DIV[@class="pp-text-1"]')
# FB_ICON_PUB = (By.XPATH, '//A[@class="fb create-loading-follow-us-icons__item"]')
FOLLOW_US_PUB = (By.XPATH, '//DIV[@class="create-loading-follow-us-text"][text()="Follow us:"]')
PUBLISH_ERROR_POP_UP = (By.XPATH, '//BUTTON[@class="ok-button"]')
BADGE_ON_PUBLISH_PREVIEW = (By.XPATH, '//DIV[@class="DownloadConfirmation__thumbnail"]//div')
ASSET_COUNT_TEXT_ON_POP_UP = (By.XPATH, '//SPAN[@class="promo__typography Dark01-col promo__typography--headline promo__typography--micro promo__typography--left"]')

# Publish Page
SELECTED_DRAFT_VIDEO = (By.XPATH, '//DIV[@class="pp-video-ratio pp-video-ratio--selected"]')
EDIT_PUBLISHED_ICON_PUBLISH_PG = (By.XPATH, '//DIV[@class="pp-video-ratio__revision"]')  # to_improve: add qaid when it is implemented by devs
BLUE_TICK_ICON = (By.XPATH, '//SPAN[@class="pp-icon pp-icon--check"]')  # to_improve: add qaid
DOWNLOAD_PUBLISHED_VIDEO = (By.XPATH, '//*[text()="Download video"]')
DOWNLOAD_HD_VIDEO = (By.XPATH, '//SPAN[@class="download-video-dropdown__option"][text()="HD"]')
PUBLISH_TO_SOCIAL = (By.XPATH, '//BUTTON[@data-qaid="publish_to_social_btn"]')
PUBLISH_TO_SOCIAL_BACK = (By.XPATH, '//BUTTON[@data-qaid="pub-header-back"]')
DOWNLOAD_IMAGE = (By.XPATH, "//*[contains(text(), 'Export image / GIF')]")
DOWNLOAD_JPEG_IMAGE = (By.XPATH, "//*[contains(text(), 'Export as JPEG')]")
DOWNLOAD_GIF_IMAGE = (By.XPATH, "//*[contains(text(), 'Export as GIF')]")
EXPORT_PHOTO_BUTTON = (By.XPATH, "//*[contains(text(), 'Export Photo')]")
EXPORT_GIF_BUTTON = (By.XPATH, "//*[contains(text(), 'Export GIF')]")
IMAGE_EXPORT_POPUP_CLOSE = (By.XPATH, "//*[contains(@class, 'pp-popup__close')]")
EMBED = (By.XPATH, "//*[contains(text(), 'Copy link / Embed')]")
EMBED_DROPDOWN_OPTION = (By.XPATH, "//*[contains(@class, 'pp-dropdown-option')]//*[contains(text(), 'Embed')]")
COPY_LINK_OPTION = (By.XPATH, '//SPAN[text()="Copy link"]')
GET_LINK = (By.XPATH, '//DIV[@id="link"]')
AUTOPLAY_CHECK_BOX = (By.XPATH, "//*[contains(@name, 'autoplay')]")
LOOP_CHECKBOX = (By.XPATH, "//*[contains(@name, 'loop')]")
EMBED_CODE = (By.XPATH, '//*[@class="embed-code"]')
COPY_TO_CLIPBOARD = (By.XPATH, "//*[contains(text(), 'Copy to Clipboard')]")
CODE_PEN_INPUT = (By.XPATH, "(//*[contains(@class, 'CodeMirror-code')])[1]")
VIDEO_IFRAME = (By.XPATH, "//video[contains(@class, 'clickable')]")
CODEPEN_HTML_INPUT = (By.XPATH, '(//*[@class=" CodeMirror-line "])[1]')
CODEPEN_PROMO_IFRAME = (By.XPATH, '//iframe[@class="result-iframe iframe-visual-update"]')
CODEPEN_PROMO_VIDEO = (By.XPATH, '//*[text()="View on Promo.com"]')
SOCIAL_BACK_LEAVE = (By.XPATH, '//BUTTON[@data-qaid="pub-leave-page-leave"]')
EDIT_VIDEO = (By.XPATH, "//button[normalize-space()='Edit video']")
CREATE_POST_BTN = (By.XPATH, '//BUTTON[@class="pp-create-post"]')
BACK_TO_EDITOR = (By.XPATH, '//DIV[@class="link__text"][text()="Back to editor"]')
PUBLISHED_ASPECT_RATIOS = (By.XPATH, "(//*[contains(@class, 'empty-video-ratio__action empty-video-ratio__action-plus')])")
UPLOAD_TO_BTN = (By.XPATH, "//*[contains(text(), 'Upload to')]")
DROPBOX_CONNECT_BTN = (By.XPATH, "//*[@data-qaid='upload_item_dropbox_connect']")
DROPBOX_DISCONNECT_BTN = (By.XPATH, '//*[@data-qaid="upload_item_dropbox_disconnect"]')
HUBSPOT_CONNECT_BTN = (By.XPATH, "//*[@data-qaid='upload_item_hubspot_connect']")
CHOOSE_HUBSPOT_RADIO_BTN = (By.XPATH, '(//*[text()="abc "]/../span)[1]')
CHOOSE_ACCOUNT_BTN = (By.XPATH, '//*[text()="Choose Account"]')
HUBSPOT_CONNECT_APP = (By.XPATH, '//*[text()="Connect app"]')
HUBSPOT_UPLOAD_FILE_ICON = (By.XPATH, "//div[@data-qaid='upload_item_hubspot_upload']")
DROPBOX_EMAIL = (By.XPATH, "//INPUT[@name='login_email']")
DROPBOX_PASSWORD = (By.XPATH, "//*[contains(@name, 'login_password')]")
DROPBOX_EMAIL_ERROR = (By.XPATH, '//*[text()="Please enter your email"]')
DROPBOX_SIGNIN_BTN = (By.XPATH, "//button[contains(@type, 'submit')]//*[contains(text(), 'Sign in')]")
DROPBOX_UPLOAD_FILE_ICON = (By.XPATH, "//div[@data-qaid='upload_item_dropbox_upload']")
DROPBOX_FOLDER = (By.XPATH, '//*[@data-qaid="folder_selected"]//div[@class="folder__title--main"]')
DROPBOX_FOLDER_PROMO = (By.XPATH, '//*[text()="./Promo.com"]')
FILE_UPLOAD_BTN = (By.XPATH, '//*[@class="manager-folder__bottom-actions__save"]')
FILE_UPLOADED = (By.XPATH, '//*[@class="folder__title--sub"][text()="File Saved!"]')
UPLOAD_DONE_BTN = (By.XPATH, '//*[@class="manager-folder__bottom-actions__done"]')
HUBSPOT_EMAIL_TXT = (By.XPATH, '//INPUT[@id="username"]')
HUBSPOT_PASS_TXT = (By.XPATH, '//INPUT[@id="password"]')
HUBSPOT_SIGNIN_BTN = (By.XPATH, '//BUTTON[@data-test-id="password-login-button"]')
WISTIA_DISCONNECT = (By.XPATH, '//*[@data-qaid="upload_item_wistia_disconnect"]')
WISTIA_CONNECT_BTN = (By.XPATH, '//*[@data-qaid="upload_item_wistia_connect"]')
WISTIA_EMAIL = (By.XPATH, '//INPUT[@id="user_email"]')
WISTIA_PASS = (By.XPATH, '//INPUT[@id="email_login_form_password"]')
WISTIA_SIGNIN_BTN = (By.XPATH, '//BUTTON[@class="AuthFormButton"]')
WISTIA_UPLOAD_FILE_ICON = (By.XPATH, "//div[@data-qaid='upload_item_wistia_upload']")
WISTIA_FILE_UPLOADED = (By.XPATH, '//*[text()="Uploaded"]')
WISTIA_AUTHORIZE = (By.XPATH, '//*[@value="Authorize"]')
GOOGLEDRIVE_DISCONNECT = (By.XPATH, "//*[contains(@data-qaid, 'upload_item_google-drive_disconnect')]")
GOOGLEDRIVE_CONNECT_BTN = (By.XPATH, "//*[contains(@data-qaid, 'upload_item_google-drive_connect')]")
HUBSPOT_OTP_FIELD = (By.XPATH, "//*[contains(@id, 'code')]")
HUBSPOT_FILE_UPLOADED = (By.XPATH, "//*[contains(@class, 'upload-to-item__action')]//*[contains(text(), 'Uploaded')]")
HUBSPOT_DISCONNECT_BTN = (By.XPATH, '//*[@data-qaid="upload_item_hubspot_disconnect"]')
CAPTCHA_VERIFY_BTN = (By.XPATH, "//button[contains(@id, 'home_children_button')]")
HUBSPOT_LOGIN_BTN = (By.XPATH, '//*[@data-key="login.form.button"]')
DROPBOX_CAPTCHA_IFRAME = (By.XPATH, '//IFRAME[@class="funcaptcha-frame"]')
DROPBOX_OTP_FIELD = (By.XPATH, '//INPUT[@class="text-input-input numeric-input"]')
DROPBOX_OTP_ENTER = (By.XPATH, '//BUTTON[text()="Enter"]')
WISTIA_VIDEOS = (By.XPATH, '//div[@data-appcues="project"]')
WISTIA_VIDEOS_DEL = (By.XPATH, '//*[@data-testid="delete-project-button"]')
WISTIA_VIDEOS_DEL_CONF = (By.XPATH, '(//*[text()="Delete Project"])[2]')
WISTIA_POP_UP_CLOSE = (By.XPATH, '//BUTTON[@aria-label="Close"]')
JS_FIDDLE_RUN_BTN = (By.XPATH, "//*[contains(@id, 'run')]")
JS_FIDDLE_IFRAME = (By.XPATH, "//iframe[@name='result']")
JS_FIDDLE_HTML_INPUT = (By.XPATH, "(//*[contains(@class, 'CodeMirror-scroll')])[2]")
HTML_VIEWER_PROMO_VIDEO = (By.XPATH, '//a[text()="View on Promo.com"]')

# Publisher and Scheduler
PUBLISHER_MAIN_HEADER = (By.XPATH, '(//div[@class="pub-account-select-page"])[1]')
FB_CONNECT_BTN = (By.XPATH, '(//DIV[@class="pub-connect-modal__item-button"])[1]')
IG_CONNECT_BTN = (By.XPATH, '(//DIV[@class="pub-connect-modal__item-button"])[2]')
YT_CONNECT_BTN = (By.XPATH, '(//DIV[@class="pub-connect-modal__item-button"])[3]')
TW_CONNECT_BTN = (By.XPATH, '(//DIV[@class="pub-connect-modal__item-button"])[4]')
LI_CONNECT_BTN = (By.XPATH, '(//DIV[@class="pub-connect-modal__item-button"])[5]')
FB_SELECT_PAGE_POP_UP = (By.XPATH, '//SPAN[text()="Select pages or ad accounts to connect"]')
FB_SELECT_PAGE = (By.XPATH, '(//*[@data-qaid="pub-account-details-name"])[1]')
FB_PAGE_SELECT_BTN = (By.XPATH, '//BUTTON[text()="Select"]')
ADD_TEXT_FOR_FB_POST = (By.XPATH, '//*[@class="pub-textarea__textarea"]')
ADD_TEXT_TO_1ST_POST = (By.XPATH, '(//*[@class="pub-textarea__textarea"])[1]')
ADD_TEXT_TO_2ND_POST = (By.XPATH, '(//*[@class="pub-textarea__textarea"])[2]')
ADD_TEXT_TO_3RD_POST = (By.XPATH, '(//*[@class="pub-textarea__textarea"])[3]')
ADD_TEXT_TO_YT_DESCRIPTION_2 = (By.XPATH, '//textarea[@data-qaid="pub-youtube-form-desc-2"]')
ADD_TEXT_TO_YT_DESCRIPTION_1 = (By.XPATH, '//textarea[@data-qaid="pub-youtube-form-desc-1"]')
ADD_TEXT_TO_YT_DESCRIPTION = (By.XPATH, '//textarea[contains(@data-qaid, "pub-youtube-form-desc")]')
ADD_VIDEO_TO_POST = (By.XPATH, '//SPAN[@class="pub-media-button__text"]')
ADD_VIDEO_POP_UP_PUBLISHER_SELECT = (By.XPATH, '(//BUTTON[@class="pub-button pub-button--primary pub-button--xs "])[1]')
PUBLISHER_REMOVE_VIDEO = (By.XPATH, '//BUTTON[@data-qaid="pub-promo-media-remove-0"]')
PUBLISH_POST_BTN = (By.XPATH, '//BUTTON[@data-qaid="pub-accounts-publish-post"]')
PUBLISH_REVIEW_H1 = (By.XPATH, '//DIV[text()="Publish Review"]')
PUBLISH_REVIEW_TITLE = (By.XPATH, '//DIV[@class="pub-publish-manager-item-status__title"]')
PUBLISH_READY_MARK = (By.XPATH, '//DIV[@data-qaid="pub-publish-manager-ready-0"]')
PUBLISH_REVIEW_BACK_TO_EDIT = (By.XPATH, '//BUTTON[@data-qaid="pub-back-to-edit"]')
FINAL_PUBLISH_POST_BTN = (By.XPATH, '//BUTTON[@data-qaid="pub-publish-post-button"]')
VIDEO_POSTED = (By.XPATH, '//DIV[@data-qaid="pub-publisher-manager-status-posted-0"]')
PUBLISH_VIEW_PLANNER_BTN = (By.XPATH, '//BUTTON[@data-qaid="pub-publish-manager-planner-btn"]')
PUBLISH_CREATE_POST_BTN = (By.XPATH, '//BUTTON[@data-qaid="pub-publish-manager-create-btn"]')
FB_PUB_ACCOUNTS_DETAILS_DROPDOWN = (By.XPATH, '//BUTTON[@data-qaid="pub-account-details-dropdown"]')
FB_PUB_ACCOUNTS_REMOVE = (By.XPATH, '//DIV[@data-qaid="pub-account-details-remove"]')
PUB_ACCOUNTS_DISCONNECT = (By.XPATH, '//BUTTON[text()="Disconnect"]')
PUB_IG_PLATFORM = (By.XPATH, '//DIV[@data-qaid="pub-platform-instagram"]')
PUB_LI_PLATFORM = (By.XPATH, '//DIV[@data-qaid="pub-platform-linkedin"]')
IG_PUB_ACCOUNT = (By.XPATH, '//*[@data-qaid="pub-account-details-name"][text()="Kasia Promote"]')
AVATAR_SOCIAL_WHEN_CONNECTED = (By.XPATH, 'div[class="pub-account-avatar pub-account-avatar--loading"] div[class="pub-account-avatar__image"]')
PUB_TWIT_PLATFORM = (By.XPATH, '//DIV[@data-qaid="pub-platform-twitter"]')
LI_CHOOSE_PRIV_ACCOUNT_CHECKBX = (By.XPATH, '(//DIV[@class="pub-connect-modal-item__icon"])[1]')
LI_CHOOSE_PAGE_CHECKBX = (By.XPATH, '(//DIV[@class="pub-connect-modal-item__icon"])[1]')
DISCARD_POST_POPUP_BTN = (By.XPATH, '//BUTTON[@class="pub-button pub-button--primary pub-button--md "]')
PUB_ACCOUNTS = (By.XPATH, '//*[@data-qaid="pub-account-details-name"]')
ADD_MULTIPLE_POSTS = (By.XPATH, '//BUTTON[@data-qaid="pub-add-post"]')
PUBLISH_POST_NOW = (By.XPATH, '//INPUT[@data-qaid="radio-button-publish"]')
PUBLISH_2ND_POST_NOW = (By.XPATH, '(//INPUT[@data-qaid="radio-button-publish"])[2]')
PUBLISH_POST_NOW_CHECKED = (By.XPATH, '//INPUT[@data-qaid="radio-button-publish"][@checked=""]')
SCHEDULE_POST_FOR_LATER = (By.XPATH, '//INPUT[@data-qaid="radio-button-schedule"]')
SCHEDULE_POST_FOR_LATER_1 = (By.XPATH, '(//INPUT[@data-qaid="radio-button-schedule"])[1]')
SCHEDULE_POST_FOR_LATER_2 = (By.XPATH, '(//INPUT[@data-qaid="radio-button-schedule"])[2]')
SCHEDULE_POST_FOR_LATER_CHECKED = (By.XPATH, '//INPUT[@data-qaid="radio-button-schedule"][@checked=""]')
SCHEDULE_CALENDAR_ICON = (By.XPATH, '//DIV[@data-qaid="schedule-radio-button"]')
DATE_PICKER_NEXT_MONTH_ARROW = (By.XPATH, '//BUTTON[normalize-space()="Next Month"]')
DATE_PICKER_PREV_MONTH_ARROW = (By.XPATH, '//BUTTON[normalize-space()="Previous Month"]')
DATE_PICKER_PREV_MONTH_DISABLED_ARROW = (By.XPATH, '//BUTTON[@class="react-datepicker__navigation react-datepicker__navigation--previous react-datepicker__navigation--previous--disabled"]')
DATE_PICKER_1ST_DAY_OF_MONTH = (By.XPATH, '//DIV[contains(@class, "react-datepicker__day react-datepicker__day--001")]')
DATE_PICKER_1ST_DAY_OF_MONTH_SELECTED = (By.XPATH, '//DIV[contains(@class, "react-datepicker__day react-datepicker__day--001 react-datepicker__day--selected")]')
DATE_PICKER_2ND_DAY_OF_MONTH = (By.XPATH, '//DIV[contains(@class, "react-datepicker__day react-datepicker__day--002")]')
DATE_PICKER_SET_TIME_DROPDOWN = (By.XPATH, '//DIV[@data-qaid="calendar-button"]')
DATE_PICKER_CHOOSE_TIME_10AM = (By.XPATH, '//LI[normalize-space()="10:00 AM"]')
DATE_PICKER_CHOOSE_TIME_1PM = (By.XPATH, '//LI[normalize-space()="1:00 PM"]')
DATE_PICKER_SCHEDULE_BTN = (By.XPATH, '//BUTTON[@data-qaid="promo-calendar-schedule"]')
DATE_PICKER_CANCEL_BTN = (By.XPATH, '//BUTTON[@data-qaid="promo-calendar-cancel"]')
DATE_PICKER_WHOLE_COMPONENT = (By.XPATH, '//DIV[@class="react-datepicker__month-container"]')
SCHEDULE_POST_FOR_LATER_DATE = (By.XPATH, '(//SPAN[@class="scheduler-form__schedule-time text-body-micro"])[1]')
PUBLISH_SUMMARY_1ST_POSTED_ITEM_STATUS = (By.XPATH, '//DIV[@data-qaid="pub-publisher-manager-status-posted-0"]')
PUBLISH_SUMMARY_2ND_POSTED_ITEM_STATUS = (By.XPATH, '//DIV[@data-qaid="pub-publisher-manager-status-posted-1"]')
SCHEDULED_ITEM_DATE = (By.XPATH, '//SPAN[@class="pub-publish-manager-item-status__title pub-post-link"]')
MAIN_PUBLISHER_PG_1ST_SOCIAL_BTN = (By.XPATH, '//DIV[@data-qaid="pub-account-select-0"]')
MAIN_PUBLISHER_PG_2ND_SOCIAL_BTN = (By.XPATH, '//DIV[@data-qaid="pub-account-select-1"]')
MAIN_PUBLISHER_PG_3RD_SOCIAL_BTN = (By.XPATH, '//DIV[@data-qaid="pub-account-select-2"]')
PUBLISHER_FIRST_AVATAR = (By.XPATH, '(//div[@class="pub-account-avatar__image"])[1]')
DUPLICATE_1ST_POST_ICON = (By.XPATH, '//BUTTON[@data-qaid="pub-duplicate-post-0"]')
DELETE_1ST_POST_ICON = (By.XPATH, '//BUTTON[@data-qaid="pub-discard-post-0"]')
DUPLICATE_2ND_POST_ICON = (By.XPATH, '//BUTTON[@data-qaid="pub-duplicate-post-1"]')
DELETE_2ND_POST_ICON = (By.XPATH, '//BUTTON[@data-qaid="pub-discard-post-1"]')

# Planner
MY_CAL_NEXT_MONTH_ARROW = (By.XPATH, '//BUTTON[@data-qaid="calendar-header-next-month-btn"]')
MY_CAL_PREV_MONTH_ARROW = (By.XPATH, '//BUTTON[@data-qaid="calendar-header-prev-month-btn"]')
MY_CAL_1ST_DAY_OF_MONTH = (By.XPATH, '(//DIV[@data-qaid="calendar-grid-date"])[1]')
MY_CAL_CURRENT_DAY = (By.XPATH, '//DIV[contains(@class, "promo-calendar-grid__item promo-calendar-grid__item--current")]')
MY_CAL_TOMORROW_DAY = (By.XPATH, '(//DIV[contains(@class, "promo-calendar-grid__item promo-calendar-grid__item--future")])[1]')
MY_CAL_TOMORROW_SCHED_ITEM = (By.XPATH, '(//DIV[contains(@class, "promo-calendar-grid__item promo-calendar-grid__item--future")])[1]/div[2]/div[1])')
MY_CAL_NEW_POST_ITEM_TODAY = (By.XPATH, '(//BUTTON[@data-qaid="planner-new-post-btn"])[1]')
MY_CAL_NEW_POST_ITEM_TOMORROW = (By.XPATH, '(//BUTTON[@data-qaid="planner-new-post-btn"])[2]')
MY_CAL_1ST_POST_ITEM = (By.XPATH, '(//DIV[@data-qaid="post_day_item"])[1]')
MY_CAL_2ND_POST_ITEM = (By.XPATH, '(//DIV[@data-qaid="post_day_item"])[2]')
MY_CAL_1ST_POST_ITEM_HOUR = (By.XPATH, '(//DIV[@class="text-title-micro post-day-item__typography-hour"])[1]')
MY_CAL_2ND_POST_ITEM_HOUR = (By.XPATH, '(//DIV[@class="text-title-micro post-day-item__typography-hour"])[2]')
MY_CAL_LIST_OF_ALL_POSTED_ITEMS = (By.XPATH, '(//DIV[@class="my-calendar-item__list"])[1]')
MY_CAL_DELETE_POST = (By.XPATH, '//DIV[@data-qaid="post_menu_item_action_delete"]')
MY_CAL_EDIT_POST = (By.XPATH, '//DIV[@data-qaid="post_menu_item_action_edit"]')
MY_CAL_RESCHEDULE_POST = (By.XPATH, '//DIV[@data-qaid="post_menu_item_action_reschedule"]')
MY_CAL_DUPLICATE_POST = (By.XPATH, '//DIV[@data-qaid="post_menu_item_duplicate_post"]')
MY_CAL_YES_DELETE_BTN = (By.XPATH, '//BUTTON[normalize-space()="Yes, delete it"]') # to_improve: change to qaid when COR1-3981 is done
MY_CAL_POST_MENU_ITEM = (By.XPATH, '//DIV[@class="post-menu-item"]')
MY_CAL_SHOW_MORE_LESS_POSTS = (By.XPATH, '//BUTTON[@class="button-small my-calendar-item__btn"]')

# Pricing Page
STANDARD_PLAN_CTA = (By.XPATH,
                     '//DIV[@class="pricing-item best-value pop-out shown"]/div[3]/div[text()="Choose Standard"]')
TOGGLE_ON = (By.XPATH, '//DIV[@class="switch-button  on"]')
TOGGLE_OFF = (By.XPATH, '//DIV[@class="switch-button  off"]')
TOGGLE_BTN = (By.XPATH, '//DIV[@class="plan-period-switch"]')
PAYMENT_CARD_IFRAME = (By.XPATH, '//IFRAME[@title="Secure card number input frame"]')
PAYMENT_EXPDATE_IFRAME = (By.XPATH, '//IFRAME[@title="Secure expiration date input frame"]')
PAYMENT_CVC_IFRAME = (By.XPATH, '//IFRAME[@title="Secure CVC input frame"]')
CARD_NUMBER_TXTBOX = (By.XPATH, '//INPUT[@class="InputElement is-empty Input Input--empty"][@name="cardnumber"]')
EXP_DATE_TXTBOX = (By.XPATH, '//INPUT[@name="exp-date"]')
CVC_TXTBOX = (By.XPATH, '//INPUT[@name="cvc"]')
PURCHASE_NOW_BTN = (By.XPATH, '//BUTTON[@class="purchase-button"][text()="Purchase Now"]')
CURRENT_PLAN = (By.XPATH, '//DIV[@class="current"]')
PRICING_CLOSE_BTN = (By.XPATH, '//BUTTON[@class="close-popup fade"]')
CREATE_NOW_CTA = (By.XPATH, '//BUTTON[@class="main-cta"][text()="Create Now"]')
PRICING_INTERCOM_IFRAME = (By.XPATH, '//IFRAME[@name="intercom-banner-frame"]')
PRICING_INTERCOM_IFRAME_BS = (By.XPATH, '//IFRAME[@class="intercom-1s2v3tz e1c099050"]')
PRICING_INTERCOM_IFRAME_CLS = (By.XPATH, '//DIV[@role="button"]')
PAYMENT_CARD_IFRAME_NEW = (By.XPATH, '//IFRAME[@class="stripe_checkout_app"]')
EDITOR_PAYMENT_CARD_IFRAME_NEW = (By.XPATH, '(//IFRAME[@class="stripe_checkout_app"])[2]')
CARD_NUMBER_TXTBOX_NEW = (By.XPATH, '//INPUT[@class="Fieldset-input Textbox-control"][@placeholder="Card number"]')
CARD_NUMBER_TXTBOX_NEW_2 = (By.XPATH, "//INPUT[@id='card_number']")
EXP_DATE_TXTBOX_NEW = (By.XPATH, '//INPUT[@class="Fieldset-input Textbox-control"][@placeholder="MM / YY"]')
EXP_DATE_TXTBOX_NEW_2 = (By.XPATH, "//INPUT[@id='cc-exp']")
CHECKOUT_POP_UP_CLOSE = (By.XPATH, '//A[@class="close right"]')
CHECKOUT_POP_UP_CLOSE2 = (By.XPATH, '//A[@class="close"]')
CVC_TXTBOX_NEW = (By.XPATH, '//INPUT[@class="Fieldset-input Textbox-control"][@placeholder="CVC"]')
CVC_TXTBOX_NEW_2 = (By.XPATH, "//INPUT[@id='cc-csc']")
PURCHASE_NOW_BTN_NEW = (By.XPATH, '//BUTTON[@class="Button-animationWrapper-child--primary Button"]')
PURCHASE_NOW_BTN_NEW_2 = (By.XPATH, '//SPAN[@class="iconTick"][text()="Purchase Now"]')
PROD_CARD_DECLINE_MESSAGE = \
    (By.XPATH, '//*[text()="Your card was declined. Your request was in live mode, but used a known test card."]')
PAYMENT_POPUP_CLOSE_BTN = (By.XPATH, '//SPAN[@class="Header-navClose"]')
TWOFA_AUTH_FRAME = (By.XPATH, '(//IFRAME[@allow="payment *"])[1]')
TWOFA_AUTH_FRAME1 = (By.XPATH, '//IFRAME[@class="AuthorizeWithUrlApp-content"]')
TWOFA_AUTH_FRAME2 = (By.XPATH, '//IFRAME[@name="acsFrame"]')
TWOFA_AUTH_BTN = (By.XPATH, '//BUTTON[@id="test-source-authorize-3ds"]')
CURRENCY_ELEMENT_AN = (By.XPATH, '//DIV[@class="pricing-item-price annual-box-label"]//Span')
CURRENCY_ELEMENT_HAS_COUPON = (By.XPATH, '//DIV[@class="pricing-item-price has-coupon annual-box-label"]//Span')
CURRENCY_ELEMENT = (By.XPATH, '//DIV[@class="pricing-item-price"]//Span')
CURRENCY_ELEMENT_PUB = (By.XPATH, '//SPAN[@class="price-amount__currency text-headline-medium"]')
PRICING_POPUP = (By.XPATH, '//DIV[@class="pricing-plans"]')
EMBED_PRICING_IFRAME = (By.XPATH, '//IFRAME[@class="embed-pricing-page"]')
PRICING_WIDGET_TOGGLE_ON = (By.XPATH, '//SPAN[@class="promo__toggle__button button-small promo__toggle__button--active"]')
PRICING_WIDGET_TOGGLE_OFF = (By.XPATH, '//SPAN[@class="promo__toggle__button button-small"]')
PRICING_WIDGET_CURRENT_PLAN = (By.XPATH, '//SPAN[@class="pricing-plan-card__title text-headline-large"]')
CHANGE_PLAN_CONF_BTN = (By.XPATH, '//BUTTON[text()="Confirm"]')
EMBED_PRICING_POPUP = (By.XPATH, '//DIV[@class="pricing-plan-cards pricing-page__cards"]')
EMBED_PRICING_POPUP_CLS = \
    (By.XPATH, '//DIV[@class="promo__icon embed-pricing-page__close-btn Dark01-bg promo__icon--extra-large"]')
CHOOSE_STANDARD_PUB = (By.XPATH, '//BUTTON[text()="Choose Standard"]')
DOLLAR_CURRENCY = (By.XPATH, '//SPAN[@class="price-amount__currency text-headline-medium"][text()="$"]')
EU_DOLLAR_CURRENCY = (By.XPATH, '//SPAN[@class="price-amount__currency text-headline-medium"][text()="€"]')
AU_DOLLAR_CURRENCY = (By.XPATH, '//SPAN[@class="price-amount__currency text-headline-medium"][text()="A$"]')
CA_DOLLAR_CURRENCY = (By.XPATH, '//SPAN[@class="price-amount__currency text-headline-medium"][text()="CA$"]')
EDITOR_PRICING_POP_UP_CLS = (By.XPATH, '//*[@class="close-button"]')
EDITOR_PRICING_POP_UP_CLS3 = (By.XPATH, '(//*[@class="close-button"])[3]')

# Brand Manager
ADD_BRAND_BTN = (By.XPATH, '//DIV[@class="text"][text()="Add Brand"]')
CREATE_BRAND_POPUP = (By.XPATH, '//DIV[@class="bm-popup-brand-fetch-popup__title"]')
LOGO_TAB = (By.XPATH, '//DIV[@class="bm-sidebar__icon bm-sidebar__icon--logo"]')
ADD_COLOR_BTN = (By.XPATH, '//DIV[@class="bm-tile__box empty"]')
ADD_LOGO_BTN = \
    (By.XPATH,
     '//DIV[@class="bm-tile__box empty"]/following::input[@accept="image/jpg, image/png, image/gif, image/jpeg"]')
WATERMARK_TAB = (By.XPATH, '//DIV[@class="bm-sidebar__icon bm-sidebar__icon--watermark"]')
COLOR_TAB = (By.XPATH, '//DIV[@class="bm-sidebar__icon bm-sidebar__icon--colors"]')
FONT_TAB = (By.XPATH, '//DIV[@class="bm-sidebar__icon bm-sidebar__icon--font"]')
BUSINESSINFO_TAB = (By.XPATH, '//DIV[@class="bm-sidebar__icon bm-sidebar__icon--businessInfo"]')
OPTIONS_BTN = (By.XPATH, '//DIV[@class="bm-header__name-options bm-options-trigger"]')
EDIT_BRAND_NAME_BTN = (By.XPATH, '//P[text()="Edit brand name"]/..')
DONE_BTN = (By.XPATH, '//BUTTON[@class="bm-header__save"]')
UPGRADE_PRO_BTN = (By.XPATH, '//DIV[@class="upgrade force-blue"][text()="Upgrade to Pro"]')
CREATE_BRAND_SKIP = \
    (By.XPATH, '//BUTTON[@class="bm-popup-brand-fetch-popup__button bm-popup-brand-fetch-popup__button--transparent"]')
BRAND_FONT_POPUP = (By.XPATH, '//DIV[@class="title"][text()="Choose your font"]')
BRAND_WATERMARK_POPUP = (By.XPATH, '//DIV[@class="title"][text()="Choose your watermark"]')
BRAND_LOGO_POPUP = (By.XPATH, '//DIV[text()="Choose your logo"]')
BRAND_NAME_TXTBOX = (By.XPATH, '//INPUT[@class="bm-popup__wizard-text-input bm-popup__wizard-input"]')
BRAND_NEXT_BTN = (By.XPATH, '//BUTTON[@class="bm-popup__button bm-popup__button--blue"]')
BRAND_DONE_BTN = (By.XPATH, '//BUTTON[@class="bm-popup__button bm-popup__button--blue"][text()="Done"]')
UPGRADE_PRO_FRAME = (By.XPATH, '(//IFRAME[@class="stripe_checkout_app"])[2]')
CONFIRM_BTN = (By.XPATH, '//BUTTON[@class="ok-button"]')
COLOR_POINTER = (By.XPATH, '//DIV[@class="saturation-pointer"]')
HUE_POINTER = (By.XPATH, '//DIV[@class="hue-pointer"]')
COLOR_TXTBOX = (By.XPATH, '//DIV[@class="color-picker__rgba"]/div/input')
COLOR_SUBMIT_BTN = (By.XPATH, '//BUTTON[@class="bm-color-picker__submit"]')
ADD_FONT_BTN = (By.XPATH, '//DIV[@class="bm-fonts-list-add-button__button"]')
BM_SEARCH_FONT_INPUT = (By.XPATH, '//DIV[@class="bm-promo-google-fonts__list"]/div[1]/input')
GOOGLE_FONT_BTN = \
    (By.XPATH, '//DIV[@class="bm-fonts-list-add-button__menu-item bm-fonts-list-add-button__menu-item--google"]')
GOLDMAN_GOOGLE_FONT = \
    (By.XPATH, '//DIV[@class="bm-font-sample bm-multi-select-fonts-list__font-sample"][text()="Goldman"]')
CASTORO_GOOGLE_FONT = \
    (By.XPATH, '//DIV[@class="bm-font-sample bm-multi-select-fonts-list__font-sample"][text()="Castoro"]')
FONT_SUBMIT_BTN = (By.XPATH, '//BUTTON[@class="bm-promo-google-fonts__button"]')
BM_TROUBLE_TXT = (By.XPATH, '//DIV[text()="Are you having any trouble with?"]')
SKIP_BM_TROUBLE_TXT = (By.XPATH, '//BUTTON[@class="_hj-OO1S1__styles__openStateToggle"]')
AT_LEAST_ONE_BRAND_DISPLAYED = (By.XPATH, '(//DIV[@class="thumbnail"])[1]')

BRAND_INFO_TXTBOX = {
    "WEBSITE_TXTBOX": (By.XPATH, '//INPUT[@class="bm-input__input"][@name="website"]'),
    "PHNUM_TEXTBOX": (By.XPATH, '//INPUT[@class="bm-input__input"][@name="phoneNumber"]'),
    "ADDRESS_TXTBOX": (By.XPATH, '//INPUT[@class="bm-input__input"][@name="address"]'),
    "FBPAGE_TXTBOX": (By.XPATH, '//INPUT[@class="bm-input__input"][@name="facebookPage"]'),
    "INSTA_TXTBOX": (By.XPATH, '//INPUT[@class="bm-input__input"][@name="instagramPage"]'),
    "TWITTER_TXTBOX": (By.XPATH, '//INPUT[@class="bm-input__input"][@name="twitterHandle"]')
 }
SAVED_BRAND_ASSERT = (By.XPATH, f'//SPAN[@class="text-input"][text()="{brand_name}"]')
BRAND_DEL_BTN = (By.XPATH, '(//DIV[@class="remove-button"])[1]')
CONFIRM_DEL_BTN = (By.XPATH, '//BUTTON[@class="ok-button"][text()="Delete"]')
EDIT_BRAND_BTN = (By.XPATH, '(//DIV[@data-qaid="dashboard_bm_edit"])')
FIRST_EDIT_BRAND_BTN = (By.XPATH, '(//DIV[@data-qaid="dashboard_bm_edit"])[1]')
DEFAULT_BRAND_CHECK = (By.XPATH, '//DIV[@class="promo-checkbox unchecked"]')
CHOOSE_IMAGE = (By.XPATH, '(//DIV[@class="bm-tile__overlay"])[1]')
CHOOSE_IMAGE2 = (By.XPATH, '(//DIV[@class="bm-tile__overlay"])[2]')
IMAGE_BRAND_NEXT_BTN = (By.XPATH, '//BUTTON[@class="bm-popup__button bm-popup__button--blue"][text()="Next"]')
BRAND_SECTION = (By.XPATH, '(//DIV[@class="thumbnail"])[1]')
BM_FONT_LANGUAGE_SET = (By.XPATH, '(//*[@class="bm-accordion__title"])[2]')
BM_FONT_ALL_LANGUAGE = (By.XPATH, '//P[text()="All languages"]')

# Facebook sign up and login
ENTER_NEW_EMAIL = (By.XPATH, '//INPUT[@id="upd-email"]')
ENTER_NEW_PASS = (By.XPATH, '//INPUT[@id="upd-password"]')
ENTER_NEW_PASS_CONFIRM = (By.XPATH, '//INPUT[@id="upd-confirm-password"]')
SAVE_CHANGES_BTN = (By.XPATH, '//SPAN[@class="md-accept"]')
CANCEL_CHANGES_BTN = (By.XPATH, '//SPAN[@class="md-cancel"]')
CONNECT_WITH_FB = (By.XPATH, '//DIV[@class="stg-social__button stg-social__button--facebook connect active"]')
DISCONNECT_FROM_FB = (By.XPATH, '//div[contains(text(),"Disconnect from Facebook")]')
DISCONNECT_FROM_GG = (By.XPATH, '//div[contains(text(),"Disconnect from Google")]')


# Dashboard
DRAFT_SHARE_BTN = (By.XPATH, '(//DIV[@data-qaid="dashboard_action_Share"])[1]')
FACEBOOK_SHARE_BTN = (By.XPATH, '//DIV[@class="SocialMediaShareButton SocialMediaShareButton--facebook"]')
FBMESSENGER_SHARE_BTN = (By.XPATH, '//DIV[@class="share-option-item "]/span[text()="Messenger"]')
TWITTER_SHARE_BTN = (By.XPATH, '//DIV[@class="SocialMediaShareButton SocialMediaShareButton--twitter"]')
WHATSAPP_SHARE_BTN = (By.XPATH, '//DIV[@class="SocialMediaShareButton SocialMediaShareButton--whatsapp"]')
LINKDIN_SHARE_BTN = (By.XPATH, '//DIV[@class="SocialMediaShareButton SocialMediaShareButton--linkedin"]')
EMAIL_SHARE_BTN = (By.XPATH, '//DIV[@class="share-option-item "]/span[text()="Email"]')
COPY_LINK_BTN = (By.XPATH, '//DIV[@class="share-option-item copy-option "]')
SHARE_CROSS_BTN = (By.XPATH, '//DIV[@class="close-button"]')
DRAFT_PUBLISH_BTN = (By.XPATH, '(//DIV[@data-qaid="dashboard_Publish"])[1]')
DRAFT_PUBLISH_CONTINUE_BTN = (By.XPATH, '//DIV[@class="download-button show fade-in"]')
VIDEO_NAME_TXTBOX = (By.XPATH, '//INPUT[@class="text-input"]')
VIDEO_NAME_EDIT = (By.XPATH, '//INPUT[@class="text-input"]')
VIDEO_NAME_EDIT_NEW = (By.XPATH, '//INPUT[@class="text-input-new"]')
DRAFT_VIDEO_NAME = (By. XPATH, '//INPUT[@name="text"]')
DRAFTED_VIDEO_NAME = (By.XPATH, f'//SPAN[text()="{drafted_video_name}"]')
# DELETE_DRAFT_VIDEO = (By.XPATH, '(//DIV[@data-qaid="dashboard_action_Delete"])[1]')
DRAFT_HOVER = (By.XPATH, '//SPAN[text()="Changed Name"]/../../../..//div[@class="popup"]')
DELETE_DRAFT_VIDEO = (By.XPATH, '//SPAN[text()="Changed Name"]/../../../..//div[@data-qaid="dashboard_action_Delete"]')
DELETE_PROJECT_BTN = (By.XPATH, '//BUTTON[@class="ok-button"]')
DRAFT_TAB = (By.XPATH, '//DIV[@data-qaid="dashboard_item_drafts"]')
FIRST_PUBLISHED_VIDEO = (By.XPATH, '(//div[@class="popup"])[1]')
EDIT_PUBLISHED_VIDEO_DASHBOARD = (By.XPATH, '//DIV[@data-qaid="dashboard_action_Edit"]')

# Templates page
SEARCH_TEMPLATES = (By.XPATH, '//INPUT[@placeholder="Search Templates"]')
TEMPLATES_GRID_PRESENCE = (By.XPATH, '//DIV[@class="templates-video-grid"]')
TEMPLATES_NOT_FOUND = (By.XPATH, '//SPAN[@class="not-found-msg"]')
temps_category = {
    r'''Valentine's Day''': (By.XPATH, r'''//A[@class="name no-children"][text()="Valentine's Day"]'''),
    'Staff Picks ⭐': (By.XPATH, '//A[@class="name no-children"][text()="Staff Picks ⭐"]'),
    'Covid-19': (By.XPATH, '//A[@class="name no-children"][text()="Covid-19"]'),
    'Real Estate': (By.XPATH, '//A[@class="name no-children"][text()="Real Estate"]'),
    'Funny': (By.XPATH, '//A[@class="name no-children"][text()="Funny"]'),
    'Inspirational / Motivational': (By.XPATH, '//A[@class="name no-children"][text()="Inspirational / Motivational"]'),
    'Video Ads': (By.XPATH, '//A[@class="name no-children"][text()="Video Ads"]'),
    'Promo Videos': (By.XPATH, '//A[@class="name no-children"][text()="Promo Videos"]'),
    'Marketing Videos': (By.XPATH, '//A[@class="name no-children"][text()="Marketing Videos"]'),
    'Facebook Ads': (By.XPATH, '//A[@class="name no-children"][text()="Facebook Ads"]'),
}
TEMPLATE_PAGE_HEADER_TITLE = (By.XPATH, '//H1[text()="Find the perfect video template"]')
START_FROM_SCRATCH = (By.XPATH, '//BUTTON[@class="btn white hero__scratch-btn"]')
ALL_TEMPLATES_CTA = (By.XPATH, '(//A[text()="All templates"])[1]')
ALL_TEMPLATES_BCRUMB = (By.XPATH, '//A[@class="breadcrumbs__item__name"][text()="All templates"]')
TEMPS_CATEGORIES = (By.XPATH, '(//H2[@class="menu-list-item-name"]/a)')
TEMPS_CATEGORIES_NEW = (By.XPATH, '(//H2[@class="menu-list-item-name"])')
BREADCRUMBS_NAME = (By.XPATH, '//SPAN[@class="breadcrumbs__item__name"]')
HOVER_TEMPLATE = (By.XPATH, '(//DIV[@class="video-item__content"])[1]')
CUSTOMIZE_TEMP_BTN = (By.XPATH, '(//BUTTON[@data-qaid="template_video_item_customize"])[1]')
PREVIEW_TEMP_BTN = (By.XPATH, '(//BUTTON[@data-qaid="template_video_item_preview"])[1]')
NEXT_PREVIEW_BTN = (By.XPATH, '(//*[@class="btn white template-video-item__preview-btn"])[1]')
RATIOS_HOV = (By.XPATH, '//DIV[@class="selected-item-name"]')
RATIO_DROPDOWN = (By.XPATH, '(//DIV[@class="selected-item-name"])[2]')
SQUARE_RATIO_ON_DROPDOWN = (By.XPATH, '//SPAN[normalize-space()="Square"]')
SHARE_BTN = (By.XPATH, '//BUTTON[text()="Share"]')
ALWAYS_WIDE_CATEGORY = (By.XPATH, '//a[normalize-space()="Always wide"]')
ALWAYS_WIDE_CATEGORY2 = (By.XPATH, '//a[normalize-space()="Always Wide"]')
TEMPL_RATIO_DROPDOWN = (By.XPATH, '(//div[@class="dropdown"])[1]')
DROPDOWN_RATIO_SELECTED_WIDE = (By.XPATH, '//div[@class="selected-item-name"][normalize-space()="Wide"]')
DROPDOWN_RATIO_SELECTED_SQUARE = (By.XPATH, '//div[@class="selected-item-name"][normalize-space()="Square"]')
TEMP_SHARE_BTN = {
    'COPY_LINK_SHARE_BTN': (By.XPATH, '//DIV[@class="share-input__copy-btn"]'),
    'Facebook': (By.XPATH, '//SPAN[@class="share-icon__title"][text()="Facebook"]'),
    'Messenger': (By.XPATH, '//SPAN[@class="share-icon__title"][text()="Messenger"]'),
    'Twitter': (By.XPATH, '//SPAN[@class="share-icon__title"][text()="Twitter"]'),
    'WhatsApp': (By.XPATH, '//SPAN[@class="share-icon__title"][text()="WhatsApp"]'),
    'Linkedin': (By.XPATH, '//SPAN[@class="share-icon__title"][text()="Linkedin"]'),
    'Email': (By.XPATH, '//SPAN[@class="share-icon__title"][text()="Email"]'),
    'Copy Link': (By.XPATH, '//SPAN[@class="share-icon__title"][text()="Copy Link"]')

}
CLOSE_SHARE_POP_UP = (By.XPATH, '//SPAN[@class="share-dialog__close-btn"]')

RATIOS = {
    'All ratios': (By.XPATH, '//SPAN[@class="dropdown-item-name"][text()="All ratios"]'),
    'Wide': (By.XPATH, '//SPAN[@class="dropdown-item-name"][text()="Wide"]'),
    'Square': (By.XPATH, '//SPAN[@class="dropdown-item-name"][text()="Square"]'),
    'Vertical': (By.XPATH, '//SPAN[@class="dropdown-item-name"][text()="Vertical"]')
}

# New pricing
CHOOSE_STARTER_BTN = (By.XPATH, "//DIV[@class='subscribe'][normalize-space()='Choose Starter']")
CHOOSE_BUSINESS_BTN = (By.XPATH, "//DIV[@class='subscribe'][normalize-space()='Choose Business']")
CHOOSE_AGENCY_BTN = (By.XPATH, "//DIV[@class='subscribe'][normalize-space()='Choose Agency']")
TOGGLE_ON_PRICING = (By.XPATH, "//div[@class='pps-handle']")
X_BUTTON_CLOSE_OFFER = (By.XPATH, "//div[@class='x-button']")
SPECIAL_OFFER_BUTTON = (By.XPATH, "//SPAN[@data-qaid='switch_to_annual_button']")
SPECIAL_OFFER_BUY_NOW_BUTTON = (By.CLASS_NAME, 'purchase-btn')  # doesn't work
SPECIAL_OFFER_TITLE_ON_LP = (By.XPATH, "//H1[normalize-space()='Promo Special Offer']")

# Plans - as function variables
# C Plans
starter_plan = (By.XPATH, "//DIV[@class='subscribe'][normalize-space()='Choose Starter']")
business_plan = (By.XPATH, "//DIV[@class='subscribe'][normalize-space()='Choose Business']")
agency_plan = (By.XPATH, "//DIV[@class='subscribe'][normalize-space()='Choose Agency']")
starter_plan_an = (By.XPATH, "//DIV[@class='pricing-item annual']//div[@class='subscribe'][normalize-space()='Choose Starter']")
business_plan_an = (By.XPATH, "//div[@class='pricing-item annual best-value suggested pop-out']//div[@class='subscribe'][normalize-space()='Choose Business']")
agency_plan_an = (By.XPATH, "//DIV[@class='pricing-item annual']//div[@class='subscribe'][normalize-space()='Choose Agency']")

# B Plans
basic_plan = (By.XPATH, "//DIV[@class='subscribe'][normalize-space()='Choose Basic']")
standard_plan = (By.XPATH, "//DIV[@class='subscribe'][normalize-space()='Choose Standard']")
pro_plan = (By.XPATH, "//DIV[@class='subscribe'][normalize-space()='Choose Pro']")
basic_plan_an = (By.XPATH, "//DIV[@class='pricing-item annual has-coupon']//div[@class='subscribe'][normalize-space()='Choose Basic']")
standard_plan_an = (By.XPATH, "//div[@class='pricing-item annual best-value suggested pop-out has-coupon']//div[@class='subscribe'][normalize-space()='Choose Standard']")
pro_plan_an = (By.XPATH, "//DIV[@class='pricing-item annual has-coupon']//div[@class='subscribe'][normalize-space()='Choose Pro']")
editor_pro_plan = (By.XPATH, '(//*[@class="subscribe force-blue"][text()="Choose Pro"])[2]')

# Cancellation flow
BILLING_CANCEL_YOUR_SUB = (By.XPATH, "//SPAN[@class='cancel-subscription-link']")
CANCEL_PLAN_CHECKBOX_EXPENSIVE = (By.XPATH, "//div[5]//div[1]//span[1]")
CANCEL_PLAN_CHECKBOX_PERFORMANCE = (By.XPATH, "//div[6]//div[1]//span[1]")
CHECKBOX_UNLIKELY = (By.XPATH, "//span[normalize-space()='Unlikely']")
CANCEL_SUBSCRIPTION_LINK = (By.XPATH, "//SPAN[@data-qaid='cancel-subscription-link']")

# Icons on billing page
BILLING_CANCEL_RED_ICON = (By.XPATH, "//DIV[@class='current-plan-icon inactive-icon']")
BILLING_UPDATE_GREEN_ICON = (By.XPATH, "//DIV[@class='current-plan-icon active-icon']")
BILLING_UPDATE_GREEN_ICON_NEW = (By.XPATH, "//DIV[@class='current-plan-icon active-icon active-icon--flip-y']")
BILLING_DOWNGRADE_GREEN_ICON = (By.XPATH, "//DIV[@class='current-plan-icon active-icon']")

# Titles
PLAN_CANCELLATION_TITLE = (By.XPATH, "//DIV[@class='ncf-title']")  # expected: Plan cancellation
SUB_PENDING_UPDATE = (By.XPATH, "//DIV[@class='small-error-msg']")  # expected: Your subscription is pending cancellation/update/downgrade.
SUB_PENDING_CANCEL = (By.XPATH, '//SPAN[@class="billing-status billing-status--pending-cancellation"]')
SUB_WILL_RENEW = (By.XPATH, "//DIV[@class='plan-description text-body-micro']")
SPECIAL_OFFER_TITLE = (By.XPATH, "//DIV[@class='ncf-title']")  # expected: A special offer just for you!
PURCHASE_OFFER_TITLE = (By.XPATH, "//DIV[@class='ncf-title']")  # expected: Thank you for purchasing a Promo plan!
SWITCH_TO_MONTHLY_PLAN_TITLE = (By.XPATH, "//div[@class='ncf-text ncf-text--semibold ncf-center']")  # expected: Do you want to switch to a monthly plan?
lITE_PLAN_OFFER_TITLE = (By.XPATH, "//div[@class='ncf-title']") # expected: Before you go…

# Buttons
CLOSE_CANCELLATION_OFFER = (By.XPATH, "//BUTTON[@class='ncf-popup__close']")
DOWNGRADE_BTN = (By.XPATH, "//BUTTON[normalize-space()='Downgrade']")
OK_BTN = (By.XPATH, "//BUTTON[normalize-space()='Ok']")
CANCEL_PLAN_NEXT_BTN = (By.XPATH, "//button[normalize-space()='Next']")
CANCEL_PLAN_BTN = (By.XPATH, "//BUTTON[normalize-space()='Cancel Plan']")
YES_I_WANT_THIS_BTN = (By.XPATH, "//BUTTON[normalize-space()='Yes, I want this!']")
YES_CANCEL_PLAN = (By.XPATH, "//BUTTON[@class='ncf-button ncf-button--transparent'][normalize-space()='Yes, cancel plan']")
CANCEL_PLAN = (By.XPATH, "//BUTTON[@class='.ncf-button'][1]")
CANCEL_PLAN_2 = (By.XPATH, "//BUTTON[@class='ncf-button ncf-button--transparent']")

# Offers
STARTER_9_DOLLAR = (By.XPATH, "//DIV[@class='ncf-plan-card ncf-plan-card--half_price_monthly_starter_c ncf-plan-card--selected']")
STARTER_18_DOLLAR = (By.XPATH, "//DIV[@class='ncf-plan-card ncf-plan-card--downgrade ncf-plan-card--selected']")
STARTER_ANNUAL_DOLLAR = (By.XPATH, "//DIV[@class='ncf-plan-card ncf-plan-card--half_price_annual_starter_c ncf-plan-card--selected']")
STARTER_AND_BUSINESS_TWO_OFFER = (By.XPATH, "//DIV[@class='ncf-offer__plans-list']")
ACCEPT_OFFER_STARTER = (By.XPATH, "//div[@class='ncf-plan-card ncf-plan-card--downgrade']")
ACCEPT_OFFER_BUSINESS = (By.XPATH, "//div[@class='ncf-plan-card ncf-plan-card--downgrade ncf-plan-card--selected']")
UNLIMITED_CLIPS_6_MONTHS = (By.XPATH, "//div[@class='ncf-plan-card-special-6m ncf-plan-card-special-6m--selected']")
STARTER_ANNUAL_72 = (By.XPATH, "//div[@class='ncf-plan-card ncf-plan-card--half_price_annual_starter_c ncf-plan-card--selected']")
BUSINESS_20_CENT_OFF = (By.XPATH, "//DIV[@class='ncf-plan-card ncf-plan-card--20_off_monthly_business ncf-plan-card--selected']")
BUSINESS_20_CENT_OFF_1 = (By.XPATH, "//DIV[@class='ncf-plan-card ncf-plan-card--20_off_keep_monthly_business ncf-plan-card--selected']")
MONTHLY_BUSINESS = (By.XPATH, "//DIV[@class='ncf-plan-card ncf-plan-card--update ncf-plan-card--selected']")
BASIC_MONTHLY_HALF_PRICE = (By.XPATH, "//DIV[@class='ncf-plan-card ncf-plan-card--half_price_monthly_basic ncf-plan-card--selected']")
lITE_PLAN = (By.XPATH,"//div[@class='ncf-plan-card ncf-plan-card--lite_plan ncf-plan-card--selected']")
BASIC_PLAN_OFFER = (By.XPATH, "//div[@class='ncf-plan-card ncf-plan-card--downgrade ncf-plan-card--selected']")
BASIC_ANNUAL_HALF_PRICE = (By.XPATH, "//div[@class='ncf-plan-card ncf-plan-card--half_price_annual_basic ncf-plan-card--selected']")
ACCEPT_OFFER_BASIC = (By.XPATH, "//div[@class='ncf-plan-card ncf-plan-card--downgrade']")
# ACCEPT_OFFER_BASIC = (By.XPATH, "//div[@class='ncf-plan-card ncf-plan-card--downgrade ncf-plan-card--higher']")
ACCEPT_OFFER_STANDARD = (By.XPATH, "//div[@class='ncf-plan-card ncf-plan-card--downgrade ncf-plan-card--selected']")
# ACCEPT_OFFER_STANDARD = (By.XPATH, "//div[@class='ncf-plan-card ncf-plan-card--downgrade ncf-plan-card--selected ncf-plan-card--higher']")
BASIC_AND_STANDARD_TWO_OFFERS = STARTER_AND_BUSINESS_TWO_OFFER
PRICE_SHOWN_TO_USER = (By.XPATH, "//div[@class='ncf-plan-card__price']")
PRICE_OFFERED_TO_USER = (By.XPATH, "//div[@class='ncf-plan-card__price-current']")
PRICE_OFFERED_TO_USER_2 = (By.XPATH, "(//div[@class='ncf-plan-card__price-current'])[2]")
PRICE_OFFERED_TO_USER_3 = (By.XPATH, "(//div[@class='ncf-plan-card-special-6m__price-current'])")
CURRENCY_SYMBOL = (By.XPATH, "(//div[@class='ncf-plan-card__price-currency'])")
CURRENCY_SYMBOL_2 = (By.XPATH, "(//div[@class='ncf-plan-card__price-currency'])[2]")
CURRENCY_SYMBOL_3 = (By.XPATH, "(//div[@class='ncf-plan-card-special-6m__price-currency'])")


# ModHeader Locators
HEADER_NAME = (By.XPATH, '//INPUT[@class="mdc-text-field__input "][@placeholder="Name"]')
HEADER_VALUE = (By.XPATH, '//INPUT[@class="mdc-text-field__input "][@placeholder="Value"]')
MODHEADER_OPTION_BTN = (By.XPATH, '//DIV[@class="data-table-cell mdc-menu-surface--anchor"]/button')
MODHEADER_OPTION_BTN_MOB = (By.XPATH, '/html/body/div[2]/div[1]/header/div/section[2]/button[2]')
HEADER_ADD_BTN = (By.XPATH, '//SPAN[@class="mdc-list-item__text "][text()="Add"]')
HEADER_ADD_BTN_MOB = (By.XPATH, '/html/body/div[2]/div[1]/header/div/section[2]/div[1]/ul/li[1]')
HEADER_NAME2 = (By.XPATH, '(//INPUT[@class="mdc-text-field__input "][@placeholder="Name"])[2]')
HEADER_VALUE2 = (By.XPATH, '(//INPUT[@class="mdc-text-field__input "][@placeholder="Value"])[2]')
HEADER_BODY_CLICK = (By.XPATH, '//BODY[@class="mdc-menu-surface--anchor"]')
INCOGNITO_TOGGLE_MODHEADER_IN_CHROME_EXTENSION_PAGE_JSPATH = \
    'document.querySelector("body > extensions-manager").shadowRoot.querySelector("#viewManager > extensions-detail-view").shadowRoot.querySelector("#allow-incognito").shadowRoot.querySelector("#crToggle").click();'


# ANIMATORS LOCATORS

CONNECT_BUTTON = (By.XPATH, "//*[contains(text(), 'Connect')]")
CHOOSE_FILE_BUTTON = (By.XPATH, "//*[contains(@type, 'file')]")


# PTV LOCATORS
# to_improve: add qaids
PTV_CREATE_VIDEO_BTN = (By.XPATH, '//DIV[@class="clp-cta-btn clp-create-xpress"]')
PTV_MY_VIDEOS_DASHBOARD_TITLE = (By.XPATH, '//DIV[@class="app-dashboard-page__my-videos"]')
PTV_CREATE_NEW_BTN = (By.XPATH, '//BUTTON[@class="btn app-button white-button"]')
PTV_FIRST_TEMPLATE = (By.XPATH, '(//LI[@class="list-item video-grid-item"])[1]')
PTV_CHECKMARK_ICON_SELECTED = (By.XPATH, '//DIV[@class="checkmark checkmark--selected list-item__checkmark"]')
PTV_NEXT_BTN = (By.XPATH, '//BUTTON[@class="btn app-button primary-button wizard-step__next-button"]')
PTV_WIZARD_STEP_2_TITLE = (By.XPATH, '//SPAN[@class="uploaded-images-selector__header-title"]')
PTV_PROJECT_NAME_EDITOR = (By.XPATH, '//DIV[@class="edited-label editor-settings__video-title"]')
PTV_EDITOR_PUBLISH_BTN = (By.XPATH, '//BUTTON[@class="btn app-button primary-button editor-page-header__publish-btn"]')
PTV_PUBLISH_PAGE_TITLE = (By.XPATH, '//DIV[@class="edited-label preview-video-player__video-title"]')
PTV_PUBLISH_PAGE_SOCIAL_TITLE = (By.XPATH, '//DIV[@class="publish-list__title"]')
PTV_SOCIALS_FB_USERNAME = (By.XPATH, '//DIV[@class="publish-list-item__username"]')
PTV_SOCIALS_FB_OPTION = (By.XPATH, '(//LI[@class="publish-list-item"])[3]')
PTV_SOCIALS_FB_OPTION2 = (By.XPATH, '//DIV[contains(text(),"Facebook")]')
PTV_SOCIALS_RECONNECT = (By.XPATH, '//button[normalize-space()="Reconnect"]')
PTV_SOCIALS_FB_PUBLISH_TO_PAGE = (By.XPATH, '(//LI[@class="publish-list-item"])[9]')
PTV_SOCIALS_FB_PAGE_ADDED = (By.XPATH, '//DIV[@class="publish-list-item__title"][normalize-space()="Promoautom"]')
PTV_FB_DESCRIPTION_INPUT = (By.XPATH, '//TEXTAREA[@class="form-input__input form-input__input--emoji"]')
PTV_FB_PUBLISH_POST = (By.XPATH, '//BUTTON[normalize-space()="Publish"]')
PTV_PUBLISH_SUCCESS_POPUP = (By.XPATH, '//DIV[@class="generic-popup generic-popup--dark message-popup video-successfully-published-popup"]')
PTV_PUBLISH_SUCCESS_POPUP_TXT = (By.XPATH, '//DIV[@class="video-successfully-published-popup__title message-popup__title"]')
PTV_PUBLISH_SUCCESS_POPUP_CLOSE = (By.XPATH, '//BUTTON[normalize-space()="Close"]')
PTV_HEADER_MY_VIDEOS = (By.XPATH, '//A[@class="nav-button header__my-videos"]')
PTV_HEADER_BACK_TO_PROMO = (By.XPATH, '//A[normalize-space()="Back to Promo"]')
PTV_NOT_SELECTED_TAB = (By.XPATH, '//DIV[@class="tab"]')
PTV_SELECTED_TAB = (By.XPATH, '//DIV[@class="tab tab--selected"]')
PTV_DASHBOARD_FIRST_PROJECT = (By.XPATH, '(//DIV[@class="dashboard-grid-item"])[1]')
PTV_DASHBOARD_DELETE_PROJECT = (By.XPATH, '//DIV[@class="menu-button__menu menu-button__menu--right"]//span[@class="action-menu-item__name"][normalize-space()="Delete"]')
PTV_POPUP_DELETE_PROJECT_BTN = (By.XPATH, '//BUTTON[normalize-space()="Yes, delete it"]')
PTV_GENERATION_PROCESS_TITLE = (By.XPATH, '//SPAN[@class="preview-loader__title"]')
PTV_H1_TITLE = (By.XPATH, '//h1[normalize-space()="Photos to Video maker"]')
PTV_FB_VICTORIA_CONNECTED = (By.XPATH, '//div[normalize-space()="Victoria Promoautom"]')
PTV_SHOPIFY_TEMPLATES = (By.CSS_SELECTOR, 'li.video-grid-item')
PTV_SHOPIFY_SOCIALS = (By.CSS_SELECTOR, 'li.publish-list-item')
PTV_PUBLISHED_VIDEOS_ALL = (By.CSS_SELECTOR, 'div.dashboard-grid-item')
