# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Execelleta Automation

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
          python-version: "3.12.3"
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bind9 dnsutils
        CHROME_DRIVER_VERSION=`curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
        curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
        echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
        sudo apt -y install google-chrome-stable
        wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
        unzip ~/chromedriver_linux64.zip -d ~/
        rm ~/chromedriver_linux64.zip
        mv -f ~/chromedriver /usr/local/bin/chromedriver
        chown root:root /usr/local/bin/chromedriver
        chmod 0755 /usr/local/bin/chromedriver
        USER_NAME=${GITLAB_USER_LOGIN//.}
        pip install virtualenv
        virtualenv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Excelleta Sanity Test
      run: |
        browser=headless_chrome pytest -s -m Sanity
